"""Product-neutral CLI exports, resolved only when their consumer needs them."""

from importlib import import_module as _import_module
from typing import TYPE_CHECKING
from typing import Any as _Any

_EXPORTS = {
    "AgentCliArgs": "loushang.harness.cli.agent_args",
    "AgentCliMode": "loushang.harness.cli.agent_args",
    "agent_cli_argument_values": "loushang.harness.cli.agent_args",
    "agent_cli_bootstrap_args": "loushang.harness.cli.agent_args",
    "agent_cli_output_mode": "loushang.harness.cli.agent_args",
    "agent_image_auto_resize": "loushang.harness.cli.agent_args",
    "agent_resource_loader_options": "loushang.harness.cli.agent_args",
    "agent_tool_selection": "loushang.harness.cli.agent_args",
    "apply_agent_offline_mode": "loushang.harness.cli.agent_args",
    "configure_agent_resource_loader": "loushang.harness.cli.agent_args",
    "cwd_bound_services_factory": "loushang.harness.cli.agent_args",
    "normalize_agent_cli_argv": "loushang.harness.cli.agent_args",
    "resolve_agent_prompt_input": "loushang.harness.cli.agent_args",
    "resolve_agent_session_dir": "loushang.harness.cli.agent_args",
    "AgentCliHostRequest": "loushang.harness.cli.agent_host",
    "AgentCliHostRunners": "loushang.harness.cli.agent_host",
    "AgentCliSessionHostBinding": "loushang.harness.cli.agent_host",
    "PreparedAgentCliHostInput": "loushang.harness.cli.agent_host",
    "PrepareHostInput": "loushang.harness.cli.agent_host",
    "prepare_agent_cli_host_input": "loushang.harness.cli.agent_host",
    "run_agent_cli_host": "loushang.harness.cli.agent_host",
    "run_agent_cli_session_host": "loushang.harness.cli.agent_host",
    "AgentCliApplicationBinding": "loushang.harness.cli.application",
    "AgentCliApplicationState": "loushang.harness.cli.application",
    "AgentCliStatePreparationContext": "loushang.harness.cli.application",
    "AgentCliStatePreparationPorts": "loushang.harness.cli.application",
    "CliApplicationPorts": "loushang.harness.cli.application",
    "CliApplicationRuntime": "loushang.harness.cli.application",
    "CliBootstrapContext": "loushang.harness.cli.application",
    "CliOutputGuard": "loushang.harness.cli.application",
    "CliParseResult": "loushang.harness.cli.application",
    "CliPhaseResult": "loushang.harness.cli.application",
    "CliRuntimeContext": "loushang.harness.cli.application",
    "CliSessionContext": "loushang.harness.cli.application",
    "build_agent_cli_application_ports": "loushang.harness.cli.application",
    "capture_cli_parse": "loushang.harness.cli.application",
    "collect_agent_cli_help_extension_flags": "loushang.harness.cli.application",
    "format_cli_error": "loushang.harness.cli.application",
    "invoke_agent_cli_runtime_builder": "loushang.harness.cli.application",
    "invoke_cli_builder": "loushang.harness.cli.application",
    "prepare_agent_cli_application_state": "loushang.harness.cli.application",
    "run_agent_cli_application": "loushang.harness.cli.application",
    "CommandExecutionError": "loushang.harness.cli.command_execution",
    "CommandExecutionRequest": "loushang.harness.cli.command_execution",
    "CommandExecutionResult": "loushang.harness.cli.command_execution",
    "execute_command": "loushang.harness.cli.command_execution",
    "format_command_execution_result": "loushang.harness.cli.command_execution",
    "json_safe_command_result": "loushang.harness.cli.command_execution",
    "CommandListingError": "loushang.harness.cli.command_listing",
    "format_command_records": "loushang.harness.cli.command_listing",
    "list_command_records": "loushang.harness.cli.command_listing",
    "DiagnosticsListingError": "loushang.harness.cli.diagnostics_listing",
    "DiagnosticsListingRequest": "loushang.harness.cli.diagnostics_listing",
    "format_diagnostic_records": "loushang.harness.cli.diagnostics_listing",
    "list_diagnostic_records": "loushang.harness.cli.diagnostics_listing",
    "ExportFormat": "loushang.harness.cli.export",
    "ExportOperationError": "loushang.harness.cli.export",
    "ExportRequest": "loushang.harness.cli.export",
    "ExportResult": "loushang.harness.cli.export",
    "ExportResultFormat": "loushang.harness.cli.export",
    "export_session": "loushang.harness.cli.export",
    "format_export_result": "loushang.harness.cli.export",
    "apply_extension_flag_values": "loushang.harness.cli.extension_flags",
    "collect_extension_flags": "loushang.harness.cli.extension_flags",
    "extension_flag_dest": "loushang.harness.cli.extension_flags",
    "extract_unknown_long_options": "loushang.harness.cli.extension_flags",
    "project_extension_flag_values": "loushang.harness.cli.extension_flags",
    "register_extension_flag_arguments": "loushang.harness.cli.extension_flags",
    "AgentCliEarlyOperationPorts": "loushang.harness.cli.host_operations",
    "CliErrorFormatter": "loushang.harness.cli.host_operations",
    "SessionListingOperationRequest": "loushang.harness.cli.host_operations",
    "StandardCliOperationRequest": "loushang.harness.cli.host_operations",
    "agent_session_listing_request": "loushang.harness.cli.host_operations",
    "agent_standard_cli_operation_request": "loushang.harness.cli.host_operations",
    "distribution_version": "loushang.harness.cli.host_operations",
    "run_agent_cli_early_operation": "loushang.harness.cli.host_operations",
    "run_agent_cli_session_listing": "loushang.harness.cli.host_operations",
    "run_command_listing_operation": "loushang.harness.cli.host_operations",
    "run_command_operation": "loushang.harness.cli.host_operations",
    "run_diagnostics_export_operation": "loushang.harness.cli.host_operations",
    "run_diagnostics_listing_operation": "loushang.harness.cli.host_operations",
    "run_export_operation": "loushang.harness.cli.host_operations",
    "run_model_listing_operation": "loushang.harness.cli.host_operations",
    "run_package_lifecycle_operation": "loushang.harness.cli.host_operations",
    "run_plugin_listing_operation": "loushang.harness.cli.host_operations",
    "run_resource_toggle_operation": "loushang.harness.cli.host_operations",
    "run_session_listing_operation": "loushang.harness.cli.host_operations",
    "run_skill_listing_operation": "loushang.harness.cli.host_operations",
    "run_standard_cli_operations": "loushang.harness.cli.host_operations",
    "AgentCliLaunchOverlay": "loushang.harness.cli.launch",
    "CliLaunchPlan": "loushang.harness.cli.launch",
    "agent_cli_launch_plan": "loushang.harness.cli.launch",
    "cli_help_belongs_on_stderr": "loushang.harness.cli.launch",
    "cli_observability_mode": "loushang.harness.cli.launch",
    "cli_output_guard_enabled": "loushang.harness.cli.launch",
    "cli_runtime_error": "loushang.harness.cli.launch",
    "cli_static_error": "loushang.harness.cli.launch",
    "resolve_effective_tui": "loushang.harness.cli.launch",
    "MachineResourceCliUsageError": "loushang.harness.cli.machine_resources",
    "extract_machine_resource_argv": "loushang.harness.cli.machine_resources",
    "run_machine_resource_command": "loushang.harness.cli.machine_resources",
    "MethodListingError": "loushang.harness.cli.method_listing",
    "MethodListingRequest": "loushang.harness.cli.method_listing",
    "MethodListingResult": "loushang.harness.cli.method_listing",
    "run_method_listing": "loushang.harness.cli.method_listing",
    "ModelListingError": "loushang.harness.cli.model_listing",
    "ModelListingRequest": "loushang.harness.cli.model_listing",
    "ModelListingResult": "loushang.harness.cli.model_listing",
    "list_model_entries": "loushang.harness.cli.model_listing",
    "MultiAgentCliCommand": "loushang.harness.cli.multiagent",
    "MultiAgentCliUsageError": "loushang.harness.cli.multiagent",
    "MultiAgentOutputFormat": "loushang.harness.cli.multiagent",
    "MultiAgentRecipesCommand": "loushang.harness.cli.multiagent",
    "MultiAgentRunCommand": "loushang.harness.cli.multiagent",
    "extract_multiagent_argv": "loushang.harness.cli.multiagent",
    "multiagent_recipes_help": "loushang.harness.cli.multiagent",
    "multiagent_run_help": "loushang.harness.cli.multiagent",
    "parse_multiagent_command": "loushang.harness.cli.multiagent",
    "resolve_multiagent_prompt": "loushang.harness.cli.multiagent",
    "resolve_multiagent_replicas": "loushang.harness.cli.multiagent",
    "write_multiagent_recipe_catalog": "loushang.harness.cli.multiagent",
    "write_multiagent_recipe_result": "loushang.harness.cli.multiagent",
    "PackageLifecycleError": "loushang.harness.cli.package_lifecycle",
    "PackageLifecycleRequest": "loushang.harness.cli.package_lifecycle",
    "PackageLifecycleResult": "loushang.harness.cli.package_lifecycle",
    "package_lifecycle_failure": "loushang.harness.cli.package_lifecycle",
    "run_package_lifecycle": "loushang.harness.cli.package_lifecycle",
    "format_package_records": "loushang.harness.cli.package_listing",
    "run_package_listing_operation": "loushang.harness.cli.package_listing",
    "build_parser": "loushang.harness.cli.parser",
    "format_agent_cli_help": "loushang.harness.cli.parser",
    "parse_args": "loushang.harness.cli.parser",
    "register_profile_arguments": "loushang.harness.cli.parser",
    "PluginListingError": "loushang.harness.cli.plugin_listing",
    "format_plugin_records": "loushang.harness.cli.plugin_listing",
    "list_plugin_records": "loushang.harness.cli.plugin_listing",
    "PluginManagementCliBinding": "loushang.harness.cli.plugin_management",
    "STANDARD_CLI_PROFILE": "loushang.harness.cli.profile",
    "CliProfile": "loushang.harness.cli.profile",
    "ResourceToggleError": "loushang.harness.cli.resource_toggles",
    "ResourceToggleRequest": "loushang.harness.cli.resource_toggles",
    "ResourceToggleResult": "loushang.harness.cli.resource_toggles",
    "agent_resource_toggle_request": "loushang.harness.cli.resource_toggles",
    "apply_resource_toggles": "loushang.harness.cli.resource_toggles",
    "report_agent_resource_settings_errors": "loushang.harness.cli.resource_toggles",
    "CliOperationHandler": "loushang.harness.cli.runtime",
    "CliOperationInsertion": "loushang.harness.cli.runtime",
    "CliOperationRuntime": "loushang.harness.cli.runtime",
    "CliOperationSequence": "loushang.harness.cli.runtime",
    "CliOperationSpec": "loushang.harness.cli.runtime",
    "CliOperationStage": "loushang.harness.cli.runtime",
    "CliOperationUnavailableError": "loushang.harness.cli.runtime",
    "compose_cli_operation_stages": "loushang.harness.cli.runtime",
    "ModelResultWarning": "loushang.harness.cli.session_configuration",
    "ModelSelectionApplier": "loushang.harness.cli.session_configuration",
    "ModelSelectionResolver": "loushang.harness.cli.session_configuration",
    "configure_agent_cli_session": "loushang.harness.cli.session_configuration",
    "SessionListingError": "loushang.harness.cli.session_listing",
    "SessionListingFormat": "loushang.harness.cli.session_listing",
    "SessionListingRequest": "loushang.harness.cli.session_listing",
    "build_session_query": "loushang.harness.cli.session_listing",
    "format_session_records": "loushang.harness.cli.session_listing",
    "list_session_records": "loushang.harness.cli.session_listing",
    "SessionResolutionRequest": "loushang.harness.cli.session_resolution",
    "agent_session_resolution_request": "loushang.harness.cli.session_resolution",
    "resolve_agent_cli_session": "loushang.harness.cli.session_resolution",
    "resolve_latest_session_file": "loushang.harness.cli.session_resolution",
    "resolve_session": "loushang.harness.cli.session_resolution",
    "SkillListingError": "loushang.harness.cli.skill_listing",
    "format_skill_records": "loushang.harness.cli.skill_listing",
    "list_skill_records": "loushang.harness.cli.skill_listing",
    "CliDomainPreparedTurn": "loushang.harness.cli.turns",
    "CliKeywordRunner": "loushang.harness.cli.turns",
    "CliPreparedTurn": "loushang.harness.cli.turns",
    "CliTurnBatchRunner": "loushang.harness.cli.turns",
    "project_domain_turns_to_cli": "loushang.harness.cli.turns",
    "run_keyword_cli_turns": "loushang.harness.cli.turns",
    "CliArgumentSpec": "loushang.harness.cli.types",
    "CliCommandSpec": "loushang.harness.cli.types",
    "CliInvocation": "loushang.harness.cli.types",
    "CliProfileError": "loushang.harness.cli.types",
    "validate_arguments": "loushang.harness.cli.types",
    "DEFAULT_VERSION_CHECK_TIMEOUT_SECONDS": "loushang.harness.cli.version_check",
    "ParsedVersion": "loushang.harness.cli.version_check",
    "VersionCheckProfile": "loushang.harness.cli.version_check",
    "VersionFetcher": "loushang.harness.cli.version_check",
    "check_for_new_package_version": "loushang.harness.cli.version_check",
    "compare_package_versions": "loushang.harness.cli.version_check",
    "get_latest_package_version": "loushang.harness.cli.version_check",
    "is_newer_package_version": "loushang.harness.cli.version_check",
}

if TYPE_CHECKING:
    from loushang.harness.cli.agent_args import (
        AgentCliArgs,
        AgentCliMode,
        agent_cli_argument_values,
        agent_cli_bootstrap_args,
        agent_cli_output_mode,
        agent_image_auto_resize,
        agent_resource_loader_options,
        agent_tool_selection,
        apply_agent_offline_mode,
        configure_agent_resource_loader,
        cwd_bound_services_factory,
        normalize_agent_cli_argv,
        resolve_agent_prompt_input,
        resolve_agent_session_dir,
    )
    from loushang.harness.cli.agent_host import (
        AgentCliHostRequest,
        AgentCliHostRunners,
        AgentCliSessionHostBinding,
        PreparedAgentCliHostInput,
        PrepareHostInput,
        prepare_agent_cli_host_input,
        run_agent_cli_host,
        run_agent_cli_session_host,
    )
    from loushang.harness.cli.application import (
        AgentCliApplicationBinding,
        AgentCliApplicationState,
        AgentCliStatePreparationContext,
        AgentCliStatePreparationPorts,
        CliApplicationPorts,
        CliApplicationRuntime,
        CliBootstrapContext,
        CliOutputGuard,
        CliParseResult,
        CliPhaseResult,
        CliRuntimeContext,
        CliSessionContext,
        build_agent_cli_application_ports,
        capture_cli_parse,
        collect_agent_cli_help_extension_flags,
        format_cli_error,
        invoke_agent_cli_runtime_builder,
        invoke_cli_builder,
        prepare_agent_cli_application_state,
        run_agent_cli_application,
    )
    from loushang.harness.cli.command_execution import (
        CommandExecutionError,
        CommandExecutionRequest,
        CommandExecutionResult,
        execute_command,
        format_command_execution_result,
        json_safe_command_result,
    )
    from loushang.harness.cli.command_listing import (
        CommandListingError,
        format_command_records,
        list_command_records,
    )
    from loushang.harness.cli.diagnostics_listing import (
        DiagnosticsListingError,
        DiagnosticsListingRequest,
        format_diagnostic_records,
        list_diagnostic_records,
    )
    from loushang.harness.cli.export import (
        ExportFormat,
        ExportOperationError,
        ExportRequest,
        ExportResult,
        ExportResultFormat,
        export_session,
        format_export_result,
    )
    from loushang.harness.cli.extension_flags import (
        apply_extension_flag_values,
        collect_extension_flags,
        extension_flag_dest,
        extract_unknown_long_options,
        project_extension_flag_values,
        register_extension_flag_arguments,
    )
    from loushang.harness.cli.host_operations import (
        AgentCliEarlyOperationPorts,
        CliErrorFormatter,
        SessionListingOperationRequest,
        StandardCliOperationRequest,
        agent_session_listing_request,
        agent_standard_cli_operation_request,
        distribution_version,
        run_agent_cli_early_operation,
        run_agent_cli_session_listing,
        run_command_listing_operation,
        run_command_operation,
        run_diagnostics_export_operation,
        run_diagnostics_listing_operation,
        run_export_operation,
        run_model_listing_operation,
        run_package_lifecycle_operation,
        run_plugin_listing_operation,
        run_resource_toggle_operation,
        run_session_listing_operation,
        run_skill_listing_operation,
        run_standard_cli_operations,
    )
    from loushang.harness.cli.launch import (
        AgentCliLaunchOverlay,
        CliLaunchPlan,
        agent_cli_launch_plan,
        cli_help_belongs_on_stderr,
        cli_observability_mode,
        cli_output_guard_enabled,
        cli_runtime_error,
        cli_static_error,
        resolve_effective_tui,
    )
    from loushang.harness.cli.machine_resources import (
        MachineResourceCliUsageError,
        extract_machine_resource_argv,
        run_machine_resource_command,
    )
    from loushang.harness.cli.method_listing import (
        MethodListingError,
        MethodListingRequest,
        MethodListingResult,
        run_method_listing,
    )
    from loushang.harness.cli.model_listing import (
        ModelListingError,
        ModelListingRequest,
        ModelListingResult,
        list_model_entries,
    )
    from loushang.harness.cli.multiagent import (
        MultiAgentCliCommand,
        MultiAgentCliUsageError,
        MultiAgentOutputFormat,
        MultiAgentRecipesCommand,
        MultiAgentRunCommand,
        extract_multiagent_argv,
        multiagent_recipes_help,
        multiagent_run_help,
        parse_multiagent_command,
        resolve_multiagent_prompt,
        resolve_multiagent_replicas,
        write_multiagent_recipe_catalog,
        write_multiagent_recipe_result,
    )
    from loushang.harness.cli.package_lifecycle import (
        PackageLifecycleError,
        PackageLifecycleRequest,
        PackageLifecycleResult,
        package_lifecycle_failure,
        run_package_lifecycle,
    )
    from loushang.harness.cli.package_listing import (
        format_package_records,
        run_package_listing_operation,
    )
    from loushang.harness.cli.parser import (
        build_parser,
        format_agent_cli_help,
        parse_args,
        register_profile_arguments,
    )
    from loushang.harness.cli.plugin_listing import (
        PluginListingError,
        format_plugin_records,
        list_plugin_records,
    )
    from loushang.harness.cli.plugin_management import PluginManagementCliBinding
    from loushang.harness.cli.profile import STANDARD_CLI_PROFILE, CliProfile
    from loushang.harness.cli.resource_toggles import (
        ResourceToggleError,
        ResourceToggleRequest,
        ResourceToggleResult,
        agent_resource_toggle_request,
        apply_resource_toggles,
        report_agent_resource_settings_errors,
    )
    from loushang.harness.cli.runtime import (
        CliOperationHandler,
        CliOperationInsertion,
        CliOperationRuntime,
        CliOperationSequence,
        CliOperationSpec,
        CliOperationStage,
        CliOperationUnavailableError,
        compose_cli_operation_stages,
    )
    from loushang.harness.cli.session_configuration import (
        ModelResultWarning,
        ModelSelectionApplier,
        ModelSelectionResolver,
        configure_agent_cli_session,
    )
    from loushang.harness.cli.session_listing import (
        SessionListingError,
        SessionListingFormat,
        SessionListingRequest,
        build_session_query,
        format_session_records,
        list_session_records,
    )
    from loushang.harness.cli.session_resolution import (
        SessionResolutionRequest,
        agent_session_resolution_request,
        resolve_agent_cli_session,
        resolve_latest_session_file,
        resolve_session,
    )
    from loushang.harness.cli.skill_listing import (
        SkillListingError,
        format_skill_records,
        list_skill_records,
    )
    from loushang.harness.cli.turns import (
        CliDomainPreparedTurn,
        CliKeywordRunner,
        CliPreparedTurn,
        CliTurnBatchRunner,
        project_domain_turns_to_cli,
        run_keyword_cli_turns,
    )
    from loushang.harness.cli.types import (
        CliArgumentSpec,
        CliCommandSpec,
        CliInvocation,
        CliProfileError,
        validate_arguments,
    )
    from loushang.harness.cli.version_check import (
        DEFAULT_VERSION_CHECK_TIMEOUT_SECONDS,
        ParsedVersion,
        VersionCheckProfile,
        VersionFetcher,
        check_for_new_package_version,
        compare_package_versions,
        get_latest_package_version,
        is_newer_package_version,
    )
else:

    def __getattr__(name: str) -> _Any:
        module = _EXPORTS.get(name)
        if module is None:
            raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
        value = getattr(_import_module(module), name)
        globals()[name] = value
        return value

    def __dir__() -> list[str]:
        return sorted(set(globals()) | set(__all__))


__all__ = [
    "AgentCliApplicationBinding",
    "AgentCliApplicationState",
    "AgentCliArgs",
    "AgentCliEarlyOperationPorts",
    "AgentCliHostRequest",
    "AgentCliHostRunners",
    "AgentCliSessionHostBinding",
    "AgentCliLaunchOverlay",
    "AgentCliMode",
    "AgentCliStatePreparationContext",
    "AgentCliStatePreparationPorts",
    "ModelResultWarning",
    "ModelSelectionApplier",
    "ModelSelectionResolver",
    "PreparedAgentCliHostInput",
    "PrepareHostInput",
    "prepare_agent_cli_host_input",
    "prepare_agent_cli_application_state",
    "run_agent_cli_application",
    "CliApplicationPorts",
    "CliApplicationRuntime",
    "CliArgumentSpec",
    "CliBootstrapContext",
    "CliCommandSpec",
    "CliDomainPreparedTurn",
    "CliInvocation",
    "CliKeywordRunner",
    "CliLaunchPlan",
    "CliErrorFormatter",
    "SessionListingOperationRequest",
    "StandardCliOperationRequest",
    "CliOperationHandler",
    "CliOperationInsertion",
    "CliOperationRuntime",
    "CliOperationSequence",
    "CliOperationSpec",
    "CliOperationStage",
    "CliOperationUnavailableError",
    "CliOutputGuard",
    "CliParseResult",
    "CliPhaseResult",
    "CliPreparedTurn",
    "CliRuntimeContext",
    "CliSessionContext",
    "build_agent_cli_application_ports",
    "CliTurnBatchRunner",
    "compose_cli_operation_stages",
    "SessionListingError",
    "SessionListingFormat",
    "SessionListingRequest",
    "build_session_query",
    "format_session_records",
    "list_session_records",
    "SkillListingError",
    "format_skill_records",
    "list_skill_records",
    "cli_help_belongs_on_stderr",
    "cli_observability_mode",
    "cli_output_guard_enabled",
    "cli_runtime_error",
    "cli_static_error",
    "resolve_effective_tui",
    "run_command_listing_operation",
    "run_command_operation",
    "run_diagnostics_listing_operation",
    "run_diagnostics_export_operation",
    "run_export_operation",
    "run_model_listing_operation",
    "run_package_lifecycle_operation",
    "run_plugin_listing_operation",
    "run_resource_toggle_operation",
    "run_session_listing_operation",
    "run_skill_listing_operation",
    "run_standard_cli_operations",
    "run_keyword_cli_turns",
    "project_domain_turns_to_cli",
    "run_agent_cli_host",
    "run_agent_cli_session_host",
    "run_agent_cli_early_operation",
    "run_agent_cli_session_listing",
    "PluginListingError",
    "PluginManagementCliBinding",
    "format_plugin_records",
    "list_plugin_records",
    "ResourceToggleError",
    "ResourceToggleRequest",
    "ResourceToggleResult",
    "apply_resource_toggles",
    "format_package_records",
    "run_package_listing_operation",
    "ModelListingError",
    "ModelListingRequest",
    "ModelListingResult",
    "list_model_entries",
    "MultiAgentCliCommand",
    "MultiAgentCliUsageError",
    "MultiAgentOutputFormat",
    "MultiAgentRecipesCommand",
    "MultiAgentRunCommand",
    "MachineResourceCliUsageError",
    "extract_machine_resource_argv",
    "extract_multiagent_argv",
    "multiagent_recipes_help",
    "multiagent_run_help",
    "parse_multiagent_command",
    "resolve_multiagent_prompt",
    "resolve_multiagent_replicas",
    "write_multiagent_recipe_catalog",
    "write_multiagent_recipe_result",
    "MethodListingError",
    "MethodListingRequest",
    "MethodListingResult",
    "run_machine_resource_command",
    "run_method_listing",
    "PackageLifecycleError",
    "PackageLifecycleRequest",
    "PackageLifecycleResult",
    "package_lifecycle_failure",
    "run_package_lifecycle",
    "SessionResolutionRequest",
    "resolve_latest_session_file",
    "resolve_session",
    "DiagnosticsListingError",
    "DiagnosticsListingRequest",
    "apply_extension_flag_values",
    "collect_agent_cli_help_extension_flags",
    "agent_cli_output_mode",
    "agent_image_auto_resize",
    "agent_cli_bootstrap_args",
    "agent_cli_argument_values",
    "agent_resource_loader_options",
    "agent_tool_selection",
    "agent_resource_toggle_request",
    "agent_session_listing_request",
    "agent_session_resolution_request",
    "resolve_agent_cli_session",
    "agent_standard_cli_operation_request",
    "distribution_version",
    "apply_agent_offline_mode",
    "capture_cli_parse",
    "agent_cli_launch_plan",
    "collect_extension_flags",
    "extension_flag_dest",
    "extract_unknown_long_options",
    "format_diagnostic_records",
    "list_diagnostic_records",
    "ExportFormat",
    "ExportOperationError",
    "ExportRequest",
    "ExportResult",
    "ExportResultFormat",
    "export_session",
    "format_export_result",
    "CommandListingError",
    "CommandExecutionError",
    "CommandExecutionRequest",
    "CommandExecutionResult",
    "execute_command",
    "format_agent_cli_help",
    "format_cli_error",
    "format_command_execution_result",
    "json_safe_command_result",
    "format_command_records",
    "list_command_records",
    "CliProfile",
    "CliProfileError",
    "STANDARD_CLI_PROFILE",
    "build_parser",
    "parse_args",
    "project_extension_flag_values",
    "register_profile_arguments",
    "register_extension_flag_arguments",
    "normalize_agent_cli_argv",
    "resolve_agent_session_dir",
    "configure_agent_cli_session",
    "configure_agent_resource_loader",
    "cwd_bound_services_factory",
    "invoke_cli_builder",
    "invoke_agent_cli_runtime_builder",
    "resolve_agent_prompt_input",
    "report_agent_resource_settings_errors",
    "validate_arguments",
    "DEFAULT_VERSION_CHECK_TIMEOUT_SECONDS",
    "ParsedVersion",
    "VersionCheckProfile",
    "VersionFetcher",
    "check_for_new_package_version",
    "compare_package_versions",
    "get_latest_package_version",
    "is_newer_package_version",
]
