"""Lazy public exports for the optional Agent session profile."""

# ruff: noqa: F401 - TYPE_CHECKING imports preserve the typed public facade.

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from loushang.harness.capabilities.commands import (
        CommandRuntimeSource,
        SessionCommandRuntime,
    )
    from loushang.harness.session.agent_adapter import (
        AgentSessionAdapterMixin,
        initialize_composed_session,
    )
    from loushang.harness.session.agent_event_router import AgentEventRouter
    from loushang.harness.session.agent_product import AgentProductSession
    from loushang.harness.session.agent_product_runtime import (
        AgentProductSessionRuntime,
        build_agent_product_session_runtime_ports,
        build_agent_session_lifecycle_hooks,
        prepare_current_agent_session,
    )
    from loushang.harness.session.application_input import (
        ApplicationInputDelivery,
        ApplicationInputRuntime,
    )
    from loushang.harness.session.bash import (
        BashCommandExecutionRuntime,
        BashCommandHook,
        BashExecutionPorts,
        BashExecutionRuntime,
        SessionCommandExecutionRuntime,
        UserBashHookResult,
        UserBashRequest,
        UserCommandHookResult,
        UserCommandRequest,
        bash_result_from_tool_result,
        command_result_from_tool_result,
    )
    from loushang.harness.session.bindings import (
        SessionExtensionBinding,
        SessionIdentityBinding,
        SessionMaintenanceBinding,
        SessionModelBinding,
    )
    from loushang.harness.session.bootstrap_activation import (
        StandardAgentSessionActivationEffects,
        activate_standard_agent_session_configuration,
        standard_agent_session_activation_plan,
    )
    from loushang.harness.session.bootstrap_configuration import (
        StandardAgentSessionConfigurationRequest,
        StandardAgentSessionConfigurationResult,
        StandardAgentSessionConfigurationRuntime,
    )
    from loushang.harness.session.bootstrap_construction import (
        AgentBootstrapRequest,
        AgentBootstrapRuntime,
        AgentProductConstructionBinding,
        AgentProductConstructionPorts,
        AgentProductConstructionRequest,
        AgentProductConstructionResult,
        AgentProductConstructionRuntime,
        AgentSessionConstructionRequest,
        AgentSessionConstructionRuntime,
    )
    from loushang.harness.session.bootstrap_services import (
        AgentSessionServices,
        BootstrapServices,
        CreateAgentSessionResult,
        build_agent_product_session_runtime,
        build_standard_agent_session_result,
        create_standard_agent_bootstrap_services,
        prepare_agent_session_services,
    )
    from loushang.harness.session.bootstrap_utils import (
        NoToolsMode,
        append_system_prompt_fragments,
        loader_append_system_prompt,
        loader_system_prompt_override,
        non_builtin_tool_names,
        normalize_no_tools,
        resolve_base_system_prompt,
        resolve_initial_active_tool_names,
        split_model_thinking_pattern,
    )
    from loushang.harness.session.changelog import (
        STANDARD_CHANGELOG_PROFILE,
        ChangelogEntry,
        ChangelogProfile,
        find_changelog_path,
        format_changelog_entries,
        parse_changelog,
        read_changelog_for_cwd,
    )
    from loushang.harness.session.command_controller import (
        BuiltinCommandExecutor,
        BuiltinCommandMatcher,
        BuiltinDescriptorProvider,
        CommandExecutionResult,
        SessionCommandController,
        SessionCommandStorePort,
        StandardSessionCommandController,
    )
    from loushang.harness.session.command_sources import (
        DiagnosticDraftRecorder,
        ExtensionCommandErrorRecorder,
        ExtensionCommandProvider,
        ExtensionCommandProviderFactory,
        ExtensionCommandResultFactory,
        ExtensionCommandSourceRuntime,
        ResourceCommandBundleProvider,
        ResourceCommandKind,
        ResourceCommandNotFoundRecorder,
        ResourceCommandResultFactory,
        ResourceCommandSourceRuntime,
    )
    from loushang.harness.session.commands.catalog import (
        STANDARD_SESSION_COMMAND_PROFILE,
        STANDARD_SESSION_COMMANDS,
        StandardSessionCommandDefinition,
        StandardSessionCommandId,
        StandardSessionCommandProfile,
        is_standard_session_command,
        list_standard_session_command_descriptors,
    )
    from loushang.harness.session.commands.execution import (
        StandardSessionCommandDisposition,
        StandardSessionCommandPorts,
        StandardSessionCommandResult,
        StandardSessionExport,
        execute_standard_session_command_async,
    )
    from loushang.harness.session.commands.projection import (
        project_standard_session_command_result,
    )
    from loushang.harness.session.composition import ProductCompactionExecutor
    from loushang.harness.session.cwd_audit import (
        CwdBoundServicesAudit,
        CwdBoundServicesAuditIssue,
        audit_cwd_bound_services,
        project_root_from_settings_base,
        record_cwd_bound_services_audit,
    )
    from loushang.harness.session.diagnostics import (
        ExtensionDiagnosticsPort,
        ExtensionDiagnosticsProvider,
        SessionDiagnosticScope,
        SessionDiagnosticScopeProvider,
        SessionDiagnosticsRuntime,
    )
    from loushang.harness.session.event_projection import (
        SUPPORTED_JSON_EVENT_VIEWS,
        JsonEventView,
        SessionEvent,
        project_session_event,
        select_events,
        shape_stream_event,
        should_emit_projected_event,
    )
    from loushang.harness.session.event_serialization import serialize_session_event
    from loushang.harness.session.event_types import (
        AgentSessionEvent,
        AutoRetryEndEvent,
        AutoRetryStartEvent,
        BranchSummaryEndEvent,
        BranchSummaryStartEvent,
        CompactionEndEvent,
        CompactionStartEvent,
        PackageProgressSessionEvent,
        QueueUpdateEvent,
        SessionInfoChangedEvent,
        ToolPolicyAuditSessionEvent,
    )
    from loushang.harness.session.export import (
        export_session_to_html,
        export_session_to_jsonl,
    )
    from loushang.harness.session.facade import (
        ApprovalPresentationLease,
        ApprovalRequestDismisser,
        ApprovalRequestPresenter,
        OutputCallback,
        RuntimeEventListener,
        SessionApprovalInteractionPort,
        SessionCommandExecutionPort,
        SessionCommandsPort,
        SessionControlPort,
        SessionEventListener,
        SessionEventProjector,
        SessionFacade,
        SessionFacadePorts,
        SessionIdentityPort,
        SessionMaintenancePort,
        SessionResourcePort,
        SessionRetryPort,
        SessionToolsPort,
        SessionTranscriptPort,
        SessionViewPort,
        require_active_session,
        require_active_session_control,
    )
    from loushang.harness.session.facade_optional import (
        SessionApplicationInputPort,
        SessionDiagnosticsPort,
        SessionExtensionPort,
        SessionModelPort,
        SessionPackagePort,
        SessionSettingsPort,
    )
    from loushang.harness.session.inspection import (
        AgentInspectionPort,
        AgentSessionInspector,
        AgentSessionState,
        AgentStateInspectionPort,
        ContextUsage,
        SessionStats,
        TokenUsageTotals,
    )
    from loushang.harness.session.inspection_projection import (
        project_fork_candidates,
        project_session_stats,
    )
    from loushang.harness.session.lifecycle import (
        DEFAULT_FORK_PROFILE,
        FileCopy,
        ForkProfile,
        ForkSelection,
        ForkTargetResolver,
        MissingCwdPolicy,
        MissingSessionCwdError,
        PreparedSessionLifecycleOperation,
        PreparedSessionOperationStateError,
        SessionCwdIssue,
        SessionLifecycleDecision,
        SessionLifecycleHooks,
        SessionLifecyclePreparationCancelledError,
        SessionLifecycleRuntime,
        SessionLifecycleStore,
        SessionLifecycleTransition,
        TransitionCandidateCallback,
        TransitionReleaseCallback,
        resolve_fork_target,
    )
    from loushang.harness.session.lifecycle_adapter import (
        SessionLifecycleOperationAdapter,
    )
    from loushang.harness.session.model_call import (
        CurrentSessionPredicate,
        SessionModelCallCapabilityConsumer,
        SessionModelCallPreparer,
        SessionModelCallRuntime,
    )
    from loushang.harness.session.model_preferences import (
        PreferredModel,
        available_model_details,
        persistence_warning_message,
        preferred_model_candidates,
        preferred_model_details,
        preferred_model_selection,
    )
    from loushang.harness.session.model_resolution import (
        DefaultModelResolution,
        classify_model_resolution_failure,
        record_default_model_unavailable,
        resolve_default_model,
        resolve_session_model,
        scoped_models_from_patterns,
    )
    from loushang.harness.session.model_selection import (
        ModelCandidates,
        ModelChoiceData,
        ModelIdentityData,
        ModelSelectionApplyResult,
        PersistModelSelection,
        apply_session_model_selection,
        ensure_usable_session_model,
        get_session_model_identity,
        get_session_model_selection,
        iter_available_model_details,
        iter_available_model_selections,
        iter_scoped_model_selections,
        model_choice_data_from_details,
        model_choice_data_from_selections,
        model_identity_data,
    )
    from loushang.harness.session.operations import (
        SessionInputCapabilities,
        SessionInputCapability,
        SessionLifecycleOperationPorts,
        SessionOperationAvailability,
        SessionOperationCapability,
        SessionOperationResolver,
        SessionOperationRuntime,
        SessionOperationUnavailableError,
        SessionPromptRequest,
        current_session_operation_resolver,
        session_operation_resolver,
    )
    from loushang.harness.session.product_runtime import (
        ProductSessionRuntime,
        ProductSessionRuntimePorts,
        dispose_session_only,
        emit_session_shutdown,
        invoke_session_factory,
        resolve_agent_transcript_fork_target,
        resolve_existing_cwd,
        session_file_from_manager,
        session_file_from_session,
        session_id_from_session,
        session_manager_ref,
    )
    from loushang.harness.session.prompt_controller import PromptController
    from loushang.harness.session.queue_controller import QueueController
    from loushang.harness.session.resource_refresh import (
        RefreshFailureRecorder,
        ResourceBundleProvider,
        ResourceLoaderPort,
        ResourceLoaderProvider,
        ResourceSettingsPort,
        ResourceSettingsProvider,
        SessionResourceRefreshRuntime,
    )
    from loushang.harness.session.rpc_operations import SessionRpcOperationBinding
    from loushang.harness.session.runtime import (
        AfterTurnPolicyPort,
        SessionRuntime,
        TranscriptRuntimePort,
        TurnPolicyPort,
    )
    from loushang.harness.session.runtime_event_views import (
        project_runtime_event_to_json_views,
        shape_runtime_event_view,
        should_emit_runtime_event_view,
    )
    from loushang.harness.session.settings import SessionSettingsBinding
    from loushang.harness.session.tool_controller import (
        SessionToolController,
        ToolActivationProfile,
        ToolController,
        create_tool_prompt_rebuilder,
    )
    from loushang.harness.session.tool_runtime import (
        AgentToolPort,
        SessionToolRuntime,
        ToolRegistryPort,
    )
    from loushang.harness.session.transcript_lifecycle import (
        AgentTranscriptSessionRuntime,
        ProductTranscriptSessionBinding,
        ProductTranscriptSessionLifecyclePorts,
        ProductTranscriptSessionLifecycleStore,
        SessionDiagnosticsProvider,
        require_session_operation_session,
    )

_EXPORT_MODULES = {
    "AgentEventRouter": "loushang.harness.session.agent_event_router",
    "AgentProductSession": "loushang.harness.session.agent_product",
    "AgentProductSessionRuntime": "loushang.harness.session.agent_product_runtime",
    "AgentSessionAdapterMixin": "loushang.harness.session.agent_adapter",
    "build_agent_product_session_runtime_ports": "loushang.harness.session.agent_product_runtime",
    "build_agent_session_lifecycle_hooks": "loushang.harness.session.agent_product_runtime",
    "prepare_current_agent_session": "loushang.harness.session.agent_product_runtime",
    "initialize_composed_session": "loushang.harness.session.agent_adapter",
    "AgentBootstrapRequest": "loushang.harness.session.bootstrap_construction",
    "AgentBootstrapRuntime": "loushang.harness.session.bootstrap_construction",
    "AgentProductConstructionBinding": "loushang.harness.session.bootstrap_construction",
    "AgentProductConstructionPorts": "loushang.harness.session.bootstrap_construction",
    "AgentProductConstructionRequest": "loushang.harness.session.bootstrap_construction",
    "AgentProductConstructionResult": "loushang.harness.session.bootstrap_construction",
    "AgentProductConstructionRuntime": "loushang.harness.session.bootstrap_construction",
    "AgentSessionConstructionRequest": "loushang.harness.session.bootstrap_construction",
    "AgentSessionConstructionRuntime": "loushang.harness.session.bootstrap_construction",
    "AgentSessionServices": "loushang.harness.session.bootstrap_services",
    "build_agent_product_session_runtime": "loushang.harness.session.bootstrap_services",
    "build_standard_agent_session_result": "loushang.harness.session.bootstrap_services",
    "create_standard_agent_bootstrap_services": "loushang.harness.session.bootstrap_services",
    "prepare_agent_session_services": "loushang.harness.session.bootstrap_services",
    "BootstrapServices": "loushang.harness.session.bootstrap_services",
    "CreateAgentSessionResult": "loushang.harness.session.bootstrap_services",
    "StandardAgentSessionActivationEffects": "loushang.harness.session.bootstrap_activation",
    "StandardAgentSessionConfigurationRequest": "loushang.harness.session.bootstrap_configuration",
    "StandardAgentSessionConfigurationResult": "loushang.harness.session.bootstrap_configuration",
    "StandardAgentSessionConfigurationRuntime": "loushang.harness.session.bootstrap_configuration",
    "activate_standard_agent_session_configuration": "loushang.harness.session.bootstrap_activation",
    "AgentInspectionPort": "loushang.harness.session.inspection",
    "AfterTurnPolicyPort": "loushang.harness.session.runtime",
    "AgentToolPort": "loushang.harness.session.tool_runtime",
    "BashCommandExecutionRuntime": "loushang.harness.session.bash",
    "BashCommandHook": "loushang.harness.session.bash",
    "BashExecutionPorts": "loushang.harness.session.bash",
    "BashExecutionRuntime": "loushang.harness.session.bash",
    "AgentSessionInspector": "loushang.harness.session.inspection",
    "AgentSessionState": "loushang.harness.session.inspection",
    "AgentStateInspectionPort": "loushang.harness.session.inspection",
    "AgentTranscriptSessionRuntime": "loushang.harness.session.transcript_lifecycle",
    "ApplicationInputDelivery": "loushang.harness.session.application_input",
    "ApplicationInputRuntime": "loushang.harness.session.application_input",
    "CwdBoundServicesAudit": "loushang.harness.session.cwd_audit",
    "CwdBoundServicesAuditIssue": "loushang.harness.session.cwd_audit",
    "audit_cwd_bound_services": "loushang.harness.session.cwd_audit",
    "project_root_from_settings_base": "loushang.harness.session.cwd_audit",
    "record_cwd_bound_services_audit": "loushang.harness.session.cwd_audit",
    "NoToolsMode": "loushang.harness.session.bootstrap_utils",
    "append_system_prompt_fragments": "loushang.harness.session.bootstrap_utils",
    "loader_append_system_prompt": "loushang.harness.session.bootstrap_utils",
    "loader_system_prompt_override": "loushang.harness.session.bootstrap_utils",
    "non_builtin_tool_names": "loushang.harness.session.bootstrap_utils",
    "normalize_no_tools": "loushang.harness.session.bootstrap_utils",
    "resolve_initial_active_tool_names": "loushang.harness.session.bootstrap_utils",
    "resolve_base_system_prompt": "loushang.harness.session.bootstrap_utils",
    "standard_agent_session_activation_plan": "loushang.harness.session.bootstrap_activation",
    "split_model_thinking_pattern": "loushang.harness.session.bootstrap_utils",
    "CommandRuntimeSource": "loushang.harness.capabilities.commands",
    "SessionCommandController": "loushang.harness.session.command_controller",
    "StandardSessionCommandController": "loushang.harness.session.command_controller",
    "CommandExecutionResult": "loushang.harness.session.command_controller",
    "SessionCommandStorePort": "loushang.harness.session.command_controller",
    "BuiltinCommandExecutor": "loushang.harness.session.command_controller",
    "BuiltinCommandMatcher": "loushang.harness.session.command_controller",
    "BuiltinDescriptorProvider": "loushang.harness.session.command_controller",
    "STANDARD_SESSION_COMMAND_PROFILE": "loushang.harness.session.commands.catalog",
    "STANDARD_SESSION_COMMANDS": "loushang.harness.session.commands.catalog",
    "STANDARD_CHANGELOG_PROFILE": "loushang.harness.session.changelog",
    "ChangelogEntry": "loushang.harness.session.changelog",
    "ChangelogProfile": "loushang.harness.session.changelog",
    "find_changelog_path": "loushang.harness.session.changelog",
    "format_changelog_entries": "loushang.harness.session.changelog",
    "parse_changelog": "loushang.harness.session.changelog",
    "read_changelog_for_cwd": "loushang.harness.session.changelog",
    "ContextUsage": "loushang.harness.session.inspection",
    "DEFAULT_FORK_PROFILE": "loushang.harness.session.lifecycle",
    "ExtensionDiagnosticsPort": "loushang.harness.session.diagnostics",
    "ExtensionDiagnosticsProvider": "loushang.harness.session.diagnostics",
    "ExtensionCommandErrorRecorder": "loushang.harness.session.command_sources",
    "ExtensionCommandProvider": "loushang.harness.session.command_sources",
    "ExtensionCommandProviderFactory": "loushang.harness.session.command_sources",
    "ExtensionCommandResultFactory": "loushang.harness.session.command_sources",
    "ExtensionCommandSourceRuntime": "loushang.harness.session.command_sources",
    "FileCopy": "loushang.harness.session.lifecycle",
    "ForkProfile": "loushang.harness.session.lifecycle",
    "ForkSelection": "loushang.harness.session.lifecycle",
    "ForkTargetResolver": "loushang.harness.session.lifecycle",
    "resolve_fork_target": "loushang.harness.session.lifecycle",
    "MissingCwdPolicy": "loushang.harness.session.lifecycle",
    "MissingSessionCwdError": "loushang.harness.session.lifecycle",
    "PreparedSessionLifecycleOperation": "loushang.harness.session.lifecycle",
    "PreparedSessionOperationStateError": "loushang.harness.session.lifecycle",
    "PreferredModel": "loushang.harness.session.model_preferences",
    "DefaultModelResolution": "loushang.harness.session.model_resolution",
    "classify_model_resolution_failure": "loushang.harness.session.model_resolution",
    "record_default_model_unavailable": "loushang.harness.session.model_resolution",
    "resolve_default_model": "loushang.harness.session.model_resolution",
    "resolve_session_model": "loushang.harness.session.model_resolution",
    "scoped_models_from_patterns": "loushang.harness.session.model_resolution",
    "available_model_details": "loushang.harness.session.model_preferences",
    "ModelCandidates": "loushang.harness.session.model_selection",
    "CurrentSessionPredicate": "loushang.harness.session.model_call",
    "SessionModelCallCapabilityConsumer": "loushang.harness.session.model_call",
    "SessionModelCallPreparer": "loushang.harness.session.model_call",
    "SessionModelCallRuntime": "loushang.harness.session.model_call",
    "ModelChoiceData": "loushang.harness.session.model_selection",
    "ModelIdentityData": "loushang.harness.session.model_selection",
    "ModelSelectionApplyResult": "loushang.harness.session.model_selection",
    "PromptController": "loushang.harness.session.prompt_controller",
    "ProductSessionRuntime": "loushang.harness.session.product_runtime",
    "ProductCompactionExecutor": "loushang.harness.session.composition",
    "ProductSessionRuntimePorts": "loushang.harness.session.product_runtime",
    "ProductTranscriptSessionLifecyclePorts": "loushang.harness.session.transcript_lifecycle",
    "ProductTranscriptSessionLifecycleStore": "loushang.harness.session.transcript_lifecycle",
    "ProductTranscriptSessionBinding": "loushang.harness.session.transcript_lifecycle",
    "PersistModelSelection": "loushang.harness.session.model_selection",
    "persistence_warning_message": "loushang.harness.session.model_preferences",
    "preferred_model_candidates": "loushang.harness.session.model_preferences",
    "preferred_model_details": "loushang.harness.session.model_preferences",
    "preferred_model_selection": "loushang.harness.session.model_preferences",
    "QueueController": "loushang.harness.session.queue_controller",
    "RefreshFailureRecorder": "loushang.harness.session.resource_refresh",
    "ResourceBundleProvider": "loushang.harness.session.resource_refresh",
    "ResourceCommandBundleProvider": "loushang.harness.session.command_sources",
    "ResourceCommandKind": "loushang.harness.session.command_sources",
    "ResourceCommandNotFoundRecorder": "loushang.harness.session.command_sources",
    "ResourceCommandResultFactory": "loushang.harness.session.command_sources",
    "ResourceCommandSourceRuntime": "loushang.harness.session.command_sources",
    "DiagnosticDraftRecorder": "loushang.harness.session.command_sources",
    "ResourceLoaderPort": "loushang.harness.session.resource_refresh",
    "ResourceLoaderProvider": "loushang.harness.session.resource_refresh",
    "ResourceSettingsPort": "loushang.harness.session.resource_refresh",
    "ResourceSettingsProvider": "loushang.harness.session.resource_refresh",
    "OutputCallback": "loushang.harness.session.facade",
    "ApprovalPresentationLease": "loushang.harness.session.facade",
    "ApprovalRequestDismisser": "loushang.harness.session.facade",
    "ApprovalRequestPresenter": "loushang.harness.session.facade",
    "RuntimeEventListener": "loushang.harness.session.facade",
    "SessionControlPort": "loushang.harness.session.facade",
    "SessionApprovalInteractionPort": "loushang.harness.session.facade",
    "require_active_session": "loushang.harness.session.facade",
    "require_active_session_control": "loushang.harness.session.facade",
    "SessionCommandExecutionPort": "loushang.harness.session.facade",
    "SessionApplicationInputPort": "loushang.harness.session.facade_optional",
    "SessionCommandExecutionRuntime": "loushang.harness.session.bash",
    "StandardSessionCommandDisposition": "loushang.harness.session.commands.execution",
    "StandardSessionCommandDefinition": "loushang.harness.session.commands.catalog",
    "StandardSessionExport": "loushang.harness.session.commands.execution",
    "StandardSessionCommandId": "loushang.harness.session.commands.catalog",
    "StandardSessionCommandPorts": "loushang.harness.session.commands.execution",
    "StandardSessionCommandProfile": "loushang.harness.session.commands.catalog",
    "StandardSessionCommandResult": "loushang.harness.session.commands.execution",
    "list_standard_session_command_descriptors": "loushang.harness.session.commands.catalog",
    "project_standard_session_command_result": "loushang.harness.session.commands.projection",
    "SessionCommandsPort": "loushang.harness.session.facade",
    "SessionCommandRuntime": "loushang.harness.capabilities.commands",
    "SessionDiagnosticsPort": "loushang.harness.session.facade_optional",
    "SessionDiagnosticsProvider": "loushang.harness.session.transcript_lifecycle",
    "SessionEventListener": "loushang.harness.session.facade",
    "SessionEventProjector": "loushang.harness.session.facade",
    "SessionFacade": "loushang.harness.session.facade",
    "SessionFacadePorts": "loushang.harness.session.facade",
    "SessionExtensionBinding": "loushang.harness.session.bindings",
    "SessionExtensionPort": "loushang.harness.session.facade_optional",
    "SessionIdentityPort": "loushang.harness.session.facade",
    "SessionIdentityBinding": "loushang.harness.session.bindings",
    "SessionMaintenancePort": "loushang.harness.session.facade",
    "SessionMaintenanceBinding": "loushang.harness.session.bindings",
    "SessionModelBinding": "loushang.harness.session.bindings",
    "SessionModelPort": "loushang.harness.session.facade_optional",
    "SessionInputCapabilities": "loushang.harness.session.operations",
    "SessionInputCapability": "loushang.harness.session.operations",
    "SessionPackagePort": "loushang.harness.session.facade_optional",
    "SessionOperationAvailability": "loushang.harness.session.operations",
    "SessionOperationCapability": "loushang.harness.session.operations",
    "SessionOperationResolver": "loushang.harness.session.operations",
    "SessionOperationRuntime": "loushang.harness.session.operations",
    "SessionOperationUnavailableError": "loushang.harness.session.operations",
    "SessionLifecycleOperationPorts": "loushang.harness.session.operations",
    "current_session_operation_resolver": "loushang.harness.session.operations",
    "session_operation_resolver": "loushang.harness.session.operations",
    "SessionLifecycleOperationAdapter": "loushang.harness.session.lifecycle_adapter",
    "SessionResourcePort": "loushang.harness.session.facade",
    "SessionRetryPort": "loushang.harness.session.facade",
    "SessionDiagnosticScope": "loushang.harness.session.diagnostics",
    "SessionDiagnosticScopeProvider": "loushang.harness.session.diagnostics",
    "SessionDiagnosticsRuntime": "loushang.harness.session.diagnostics",
    "SessionRuntime": "loushang.harness.session.runtime",
    "SessionSettingsBinding": "loushang.harness.session.settings",
    "SessionSettingsPort": "loushang.harness.session.facade_optional",
    "SessionPromptRequest": "loushang.harness.session.operations",
    "SessionRpcOperationBinding": "loushang.harness.session.rpc_operations",
    "SessionStats": "loushang.harness.session.inspection",
    "project_fork_candidates": "loushang.harness.session.inspection_projection",
    "project_session_stats": "loushang.harness.session.inspection_projection",
    "SessionResourceRefreshRuntime": "loushang.harness.session.resource_refresh",
    "dispose_session_only": "loushang.harness.session.product_runtime",
    "emit_session_shutdown": "loushang.harness.session.product_runtime",
    "invoke_session_factory": "loushang.harness.session.product_runtime",
    "resolve_agent_transcript_fork_target": "loushang.harness.session.product_runtime",
    "resolve_existing_cwd": "loushang.harness.session.product_runtime",
    "session_file_from_manager": "loushang.harness.session.product_runtime",
    "session_file_from_session": "loushang.harness.session.product_runtime",
    "session_id_from_session": "loushang.harness.session.product_runtime",
    "session_manager_ref": "loushang.harness.session.product_runtime",
    "SessionToolRuntime": "loushang.harness.session.tool_runtime",
    "SessionToolController": "loushang.harness.session.tool_controller",
    "ToolController": "loushang.harness.session.tool_controller",
    "ToolActivationProfile": "loushang.harness.session.tool_controller",
    "create_tool_prompt_rebuilder": "loushang.harness.session.tool_controller",
    "SessionToolsPort": "loushang.harness.session.facade",
    "SessionCwdIssue": "loushang.harness.session.lifecycle",
    "SessionLifecycleDecision": "loushang.harness.session.lifecycle",
    "SessionLifecycleHooks": "loushang.harness.session.lifecycle",
    "SessionLifecyclePreparationCancelledError": "loushang.harness.session.lifecycle",
    "SessionLifecycleRuntime": "loushang.harness.session.lifecycle",
    "SessionLifecycleStore": "loushang.harness.session.lifecycle",
    "SessionLifecycleTransition": "loushang.harness.session.lifecycle",
    "TransitionCandidateCallback": "loushang.harness.session.lifecycle",
    "TransitionReleaseCallback": "loushang.harness.session.lifecycle",
    "TranscriptRuntimePort": "loushang.harness.session.runtime",
    "SessionTranscriptPort": "loushang.harness.session.facade",
    "ToolRegistryPort": "loushang.harness.session.tool_runtime",
    "TokenUsageTotals": "loushang.harness.session.inspection",
    "TurnPolicyPort": "loushang.harness.session.runtime",
    "UserCommandHookResult": "loushang.harness.session.bash",
    "UserCommandRequest": "loushang.harness.session.bash",
    "UserBashHookResult": "loushang.harness.session.bash",
    "UserBashRequest": "loushang.harness.session.bash",
    "SessionViewPort": "loushang.harness.session.facade",
    "apply_session_model_selection": "loushang.harness.session.model_selection",
    "command_result_from_tool_result": "loushang.harness.session.bash",
    "bash_result_from_tool_result": "loushang.harness.session.bash",
    "execute_standard_session_command_async": "loushang.harness.session.commands.execution",
    "ensure_usable_session_model": "loushang.harness.session.model_selection",
    "get_session_model_identity": "loushang.harness.session.model_selection",
    "get_session_model_selection": "loushang.harness.session.model_selection",
    "iter_available_model_details": "loushang.harness.session.model_selection",
    "iter_available_model_selections": "loushang.harness.session.model_selection",
    "iter_scoped_model_selections": "loushang.harness.session.model_selection",
    "model_choice_data_from_details": "loushang.harness.session.model_selection",
    "model_choice_data_from_selections": "loushang.harness.session.model_selection",
    "model_identity_data": "loushang.harness.session.model_selection",
    "is_standard_session_command": "loushang.harness.session.commands.catalog",
    "require_session_operation_session": "loushang.harness.session.transcript_lifecycle",
    "AgentSessionEvent": "loushang.harness.session.event_types",
    "AutoRetryEndEvent": "loushang.harness.session.event_types",
    "AutoRetryStartEvent": "loushang.harness.session.event_types",
    "BranchSummaryEndEvent": "loushang.harness.session.event_types",
    "BranchSummaryStartEvent": "loushang.harness.session.event_types",
    "CompactionEndEvent": "loushang.harness.session.event_types",
    "CompactionStartEvent": "loushang.harness.session.event_types",
    "JsonEventView": "loushang.harness.session.event_projection",
    "PackageProgressSessionEvent": "loushang.harness.session.event_types",
    "QueueUpdateEvent": "loushang.harness.session.event_types",
    "SUPPORTED_JSON_EVENT_VIEWS": "loushang.harness.session.event_projection",
    "SessionEvent": "loushang.harness.session.event_projection",
    "SessionInfoChangedEvent": "loushang.harness.session.event_types",
    "ToolPolicyAuditSessionEvent": "loushang.harness.session.event_types",
    "project_runtime_event_to_json_views": "loushang.harness.session.runtime_event_views",
    "project_session_event": "loushang.harness.session.event_projection",
    "select_events": "loushang.harness.session.event_projection",
    "serialize_session_event": "loushang.harness.session.event_serialization",
    "shape_runtime_event_view": "loushang.harness.session.runtime_event_views",
    "shape_stream_event": "loushang.harness.session.event_projection",
    "should_emit_projected_event": "loushang.harness.session.event_projection",
    "should_emit_runtime_event_view": "loushang.harness.session.runtime_event_views",
    "export_session_to_html": "loushang.harness.session.export",
    "export_session_to_jsonl": "loushang.harness.session.export",
}


def __getattr__(name: str) -> Any:
    """Resolve a public symbol without eagerly loading the whole profile."""

    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_EXPORT_MODULES})


__all__ = list(_EXPORT_MODULES)
