from __future__ import annotations

import argparse
import sys
import tomllib
from pathlib import Path

REPOSITORY_ROOT = Path(__file__).resolve().parents[2]
SOURCE_ROOT = REPOSITORY_ROOT / "src" / "loushang"
PYPROJECT_PATH = REPOSITORY_ROOT / "pyproject.toml"
OUTPUT_PATH = (
    REPOSITORY_ROOT
    / "docs"
    / "internals"
    / "architecture"
    / "generated"
    / "current-package-dependencies.md"
)


def _dependency_graph() -> dict[str, tuple[str, ...]]:
    source_parent = str(REPOSITORY_ROOT / "src")
    if source_parent not in sys.path:
        sys.path.insert(0, source_parent)

    from loushang.coding.arch import analyze_import_graph

    observed = analyze_import_graph(
        SOURCE_ROOT,
        package_prefix="loushang",
        granularity="subsystem",
        imports="all",
        cache_enabled=False,
    )
    prefix = "loushang."
    package_nodes = tuple(
        sorted(
            node.id.removeprefix(prefix)
            for node in observed.nodes
            if node.id.startswith(prefix) and "." not in node.id.removeprefix(prefix)
        )
    )
    package_set = frozenset(package_nodes)
    dependencies = {package: set() for package in package_nodes}
    for edge in observed.edges:
        if not edge.source.startswith(prefix) or not edge.target.startswith(prefix):
            continue
        source = edge.source.removeprefix(prefix)
        target = edge.target.removeprefix(prefix)
        if source in package_set and target in package_set and source != target:
            dependencies[source].add(target)
    return {
        package: tuple(sorted(dependencies[package])) for package in package_nodes
    }


def _console_scripts() -> dict[str, str]:
    payload = tomllib.loads(PYPROJECT_PATH.read_text(encoding="utf-8"))
    scripts = payload.get("project", {}).get("scripts", {})
    return {str(name): str(target) for name, target in sorted(scripts.items())}


def _node_id(package: str) -> str:
    return f"PKG_{package.upper().replace('-', '_')}"


def render() -> str:
    graph = _dependency_graph()
    packages = tuple(graph)
    scripts = _console_scripts()

    lines = [
        "# Current Observed Package Dependencies",
        "",
        "<!-- Generated by scripts/architecture/render_current_package_dependencies.py. -->",
        "<!-- Do not edit this file manually. -->",
        "",
        "## Status",
        "",
        "- Authority: generated — Current package/import fact",
        "- Design status: not-applicable",
        "- Implementation status: not-applicable",
        "- Sources: `loushang.coding.arch`, `src/loushang/**/*.py`, `pyproject.toml`",
        "",
        "This document records physical Python packages and source-observed import",
        "dependency edges classified by `coding.arch`.",
        "It is not the semantic runtime sequence and",
        "does not make an observed dependency architecturally desirable. Intended",
        "and forbidden direction remains governed by architecture tests and accepted",
        "scope boundaries.",
        "",
        "`A --> B` means Python source in `loushang.A` directly expresses an",
        "eager, typing, deferred, or lazy-export dependency on `loushang.B`.",
        "Categories and duplicate edges are collapsed; transitive dependencies are",
        "not drawn.",
        "",
        "## Observed Graph",
        "",
        "```mermaid",
        "graph TD",
    ]

    for package in packages:
        lines.append(f'    {_node_id(package)}["loushang.{package}"]')
    lines.append("")
    for source in packages:
        for target in graph[source]:
            lines.append(f"    {_node_id(source)} --> {_node_id(target)}")
    lines.extend(["```", "", "## Observed Dependency Table", ""])
    lines.extend(["| Package | Direct Loushang dependencies |", "| --- | --- |"])
    for package in packages:
        dependencies = ", ".join(f"`loushang.{item}`" for item in graph[package])
        lines.append(f"| `loushang.{package}` | {dependencies or 'None'} |")

    lines.extend(["", "## Console Entrypoints", ""])
    lines.extend(["| Command | Implementation |", "| --- | --- |"])
    for name, target in scripts.items():
        lines.append(f"| `{name}` | `{target}` |")

    lines.extend(
        [
            "",
            "## Interpretation Rules",
            "",
            "- This graph describes distribution-local physical imports, not Product",
            "  Capability dependencies or ownership by itself.",
            "- Compatibility packages appear while they contain Python source, even if",
            "  their long-term target is removal.",
            "- A missing edge does not prove that two scopes never interact; injected",
            "  ports and runtime values may avoid direct imports.",
            "- A new edge must still satisfy `tests/architecture/` and the relevant",
            "  parent/child scope contracts.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the checked-in generated document is stale.",
    )
    args = parser.parse_args()
    rendered = render()

    if args.check:
        if not OUTPUT_PATH.exists():
            print(f"missing generated architecture fact: {OUTPUT_PATH}", file=sys.stderr)
            return 1
        current = OUTPUT_PATH.read_text(encoding="utf-8")
        if current != rendered:
            print(
                "generated architecture fact is stale; run "
                "scripts/architecture/render_current_package_dependencies.py",
                file=sys.stderr,
            )
            return 1
        return 0

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
