from __future__ import annotations

import argparse
import sys
import xml.etree.ElementTree as ET
from collections.abc import Callable
from pathlib import Path

CORE_EXCLUDED_PREFIXES = ("protocols/",)
PRODUCTION_ADAPTER_FILES = frozenset({
    "protocols/anthropic_messages.py",
    "protocols/openai_chat_completions.py",
    "protocols/openai_responses.py",
})
ADAPTER_AGGREGATE_FILES = PRODUCTION_ADAPTER_FILES | frozenset({
    "protocols/_anthropic.py",
    "protocols/_openai_responses.py",
    "protocols/_helpers.py",
})


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "coverage_xml",
        nargs="?",
        default=".artifacts/ai/coverage.xml",
        help="Cobertura XML generated by pytest-cov.",
    )
    parser.add_argument("--core-min", type=float, default=90.0)
    parser.add_argument("--adapter-min", type=float, default=85.0)
    args = parser.parse_args(argv)

    try:
        results = check_coverage_targets(
            Path(args.coverage_xml),
            core_min=args.core_min,
            adapter_min=args.adapter_min,
        )
    except Exception as exc:
        print(f"ERROR coverage target check failed: {exc}", file=sys.stderr)
        return 1

    for result in results:
        print(
            f"{result.name}: {result.covered}/{result.valid} = "
            f"{result.percent:.2f}% (min {result.minimum:.2f}%)"
        )
    failures = [result for result in results if result.percent < result.minimum]
    if failures:
        for failure in failures:
            print(
                f"ERROR {failure.name} coverage {failure.percent:.2f}% "
                f"is below {failure.minimum:.2f}%",
                file=sys.stderr,
            )
        return 1
    print("OK coverage targets")
    return 0


class CoverageResult:
    def __init__(self, name: str, covered: int, valid: int, minimum: float) -> None:
        self.name = name
        self.covered = covered
        self.valid = valid
        self.minimum = minimum

    @property
    def percent(self) -> float:
        if self.valid == 0:
            return 100.0
        return self.covered / self.valid * 100


def check_coverage_targets(
    coverage_xml: Path,
    *,
    core_min: float = 90.0,
    adapter_min: float = 85.0,
) -> list[CoverageResult]:
    rows = _read_coverage_rows(coverage_xml)
    filenames = {filename for filename, _covered, _valid in rows}
    missing_adapters = sorted(ADAPTER_AGGREGATE_FILES - filenames)
    if missing_adapters:
        raise RuntimeError(f"missing adapter coverage rows: {missing_adapters}")
    return [
        _bucket(
            "ai-runtime-core",
            rows,
            lambda filename: not filename.startswith(CORE_EXCLUDED_PREFIXES),
            core_min,
        ),
        _bucket(
            "provider-adapters",
            rows,
            lambda filename: filename in ADAPTER_AGGREGATE_FILES,
            adapter_min,
        ),
        _bucket(
            "production-adapter-modules",
            rows,
            lambda filename: filename in PRODUCTION_ADAPTER_FILES,
            adapter_min,
        ),
    ]


def _read_coverage_rows(coverage_xml: Path) -> list[tuple[str, int, int]]:
    if not coverage_xml.exists():
        raise FileNotFoundError(coverage_xml)
    root = ET.parse(coverage_xml).getroot()
    rows: list[tuple[str, int, int]] = []
    for class_node in root.findall(".//class"):
        filename = class_node.attrib["filename"]
        line_nodes = class_node.findall("./lines/line")
        valid = len(line_nodes)
        covered = sum(
            1 for line_node in line_nodes if int(line_node.attrib.get("hits", "0")) > 0
        )
        rows.append((filename, covered, valid))
    if not rows:
        raise RuntimeError("coverage XML contains no class rows")
    return rows


def _bucket(
    name: str,
    rows: list[tuple[str, int, int]],
    predicate: Callable[[str], bool],
    minimum: float,
) -> CoverageResult:
    selected = [row for row in rows if predicate(row[0])]
    if not selected:
        raise RuntimeError(f"coverage bucket {name!r} matched no files")
    covered = sum(row[1] for row in selected)
    valid = sum(row[2] for row in selected)
    return CoverageResult(name, covered, valid, minimum)


if __name__ == "__main__":
    raise SystemExit(main())
