"""Internal, inert Plugin management contracts.

This package is intentionally absent from the public Plugin authoring surface.
"""

from loushang.harness.plugin_management.ledger import (
    PluginDesiredStateLedger,
    PluginDesiredStateSnapshotV1,
    PluginLifecycleError,
)
from loushang.harness.plugin_management.operations import (
    PLUGIN_MANAGEMENT_COMMAND_VERSION,
    PLUGIN_MANAGEMENT_OPERATION_EVENT_VERSION,
    PLUGIN_MANAGEMENT_OPERATION_RESULT_VERSION,
    PluginManagementCommandV1,
    PluginManagementOperationEventV1,
    PluginManagementOperationResultV1,
)
from loushang.harness.plugin_management.records import (
    PLUGIN_DESIRED_SELECTION_VERSION,
    PLUGIN_DESIRED_STATE_MUTATION_VERSION,
    PLUGIN_DESIRED_STATE_TRANSITION_VERSION,
    PLUGIN_INSTALLATION_KEY_VERSION,
    PLUGIN_INSTALLATION_STATE_VERSION,
    PLUGIN_PACKAGE_REVISION_REF_VERSION,
    PluginDesiredSelectionV1,
    PluginDesiredStateMutationV1,
    PluginDesiredStateTransitionV1,
    PluginInstallationKeyV1,
    PluginInstallationStateV1,
    PluginPackageRevisionRefV1,
)
from loushang.harness.plugin_management.retirement import (
    PLUGIN_RETIREMENT_INTENT_RECORD_VERSION,
    PLUGIN_RETIREMENT_INTENT_VERSION,
    PluginRetirementError,
    PluginRetirementIntentLedger,
    PluginRetirementIntentRecordV1,
    PluginRetirementIntentSnapshotV1,
    PluginRetirementIntentV1,
    PluginRetirementRecordCodecError,
)
from loushang.harness.plugin_management.service import (
    PluginManagementError,
    PluginManagementService,
)
from loushang.harness.plugin_management.updates import (
    PLUGIN_DESIRED_STATE_UPDATE_MUTATION_VERSION,
    PLUGIN_DESIRED_STATE_UPDATE_TRANSITION_RECORD_VERSION,
    PLUGIN_MANAGEMENT_UPDATE_COMMAND_VERSION,
    PLUGIN_MIGRATION_FENCE_VERSION,
    PLUGIN_UPDATE_OPERATION_EVENT_VERSION,
    PLUGIN_UPDATE_OPERATION_RESULT_VERSION,
    PLUGIN_UPDATE_RESTART_REQUIREMENT_VERSION,
    PluginDesiredStateUpdateMutationV1,
    PluginDesiredStateUpdateTransitionV2,
    PluginManagementUpdateCommandV2,
    PluginMigrationFenceV1,
    PluginUpdateOperationEventV2,
    PluginUpdateOperationResultV2,
    PluginUpdateRestartRequirementV1,
)

__all__ = [
    "PLUGIN_DESIRED_SELECTION_VERSION",
    "PLUGIN_DESIRED_STATE_MUTATION_VERSION",
    "PLUGIN_DESIRED_STATE_TRANSITION_VERSION",
    "PLUGIN_DESIRED_STATE_UPDATE_MUTATION_VERSION",
    "PLUGIN_DESIRED_STATE_UPDATE_TRANSITION_RECORD_VERSION",
    "PLUGIN_INSTALLATION_KEY_VERSION",
    "PLUGIN_INSTALLATION_STATE_VERSION",
    "PLUGIN_MANAGEMENT_COMMAND_VERSION",
    "PLUGIN_MANAGEMENT_OPERATION_EVENT_VERSION",
    "PLUGIN_MANAGEMENT_OPERATION_RESULT_VERSION",
    "PLUGIN_MANAGEMENT_UPDATE_COMMAND_VERSION",
    "PLUGIN_MIGRATION_FENCE_VERSION",
    "PLUGIN_PACKAGE_REVISION_REF_VERSION",
    "PLUGIN_RETIREMENT_INTENT_RECORD_VERSION",
    "PLUGIN_RETIREMENT_INTENT_VERSION",
    "PLUGIN_UPDATE_OPERATION_EVENT_VERSION",
    "PLUGIN_UPDATE_OPERATION_RESULT_VERSION",
    "PLUGIN_UPDATE_RESTART_REQUIREMENT_VERSION",
    "PluginDesiredStateLedger",
    "PluginDesiredSelectionV1",
    "PluginDesiredStateSnapshotV1",
    "PluginDesiredStateMutationV1",
    "PluginDesiredStateTransitionV1",
    "PluginDesiredStateUpdateMutationV1",
    "PluginDesiredStateUpdateTransitionV2",
    "PluginInstallationKeyV1",
    "PluginInstallationStateV1",
    "PluginLifecycleError",
    "PluginManagementCommandV1",
    "PluginManagementError",
    "PluginManagementOperationEventV1",
    "PluginManagementOperationResultV1",
    "PluginManagementService",
    "PluginManagementUpdateCommandV2",
    "PluginMigrationFenceV1",
    "PluginPackageRevisionRefV1",
    "PluginRetirementError",
    "PluginRetirementIntentLedger",
    "PluginRetirementIntentRecordV1",
    "PluginRetirementIntentSnapshotV1",
    "PluginRetirementIntentV1",
    "PluginRetirementRecordCodecError",
    "PluginUpdateOperationEventV2",
    "PluginUpdateOperationResultV2",
    "PluginUpdateRestartRequirementV1",
]
