"""Product-neutral AppHost A0 catalog and routing facade.

A0.2 adds an explicit admitted catalog and candidate router. It still contains
no live runtime owner, profile composer, launcher, or Product activation path.
"""

from .catalog import AppHostCatalogV1
from .contracts import (
    APPHOST_CONTRACT_VERSION,
    SESSION_IDENTITY_ENVELOPE_VERSION,
    AdmissionGenerationLeaseV1,
    AdmissionGenerationSourceV1,
    AdmissionIdentityV1,
    AppHostAdmissionSubjectKind,
    AppHostCatalogInputV1,
    AppHostComponent,
    AppHostLifecycleTransition,
    AppHostObservationSinkV1,
    AppHostObservationV1,
    ClaimedSessionCandidateV1,
    OpenedProductCandidateV1,
    PreparedProductRouteV1,
    ProductCandidateValidatorV1,
    ProductCompatibilityImporterV1,
    ProductDescriptorV1,
    ProductFactoryV1,
    ProductProfileBindingV1,
    ProductRegistrationV1,
    ProfileDescriptorV1,
    ProfileFactoryV1,
    ProfileLeaseV1,
    ProfileRegistrationV1,
    ScopedProductRuntimeV1,
    SessionBindingKeyV1,
    SessionCandidateLeaseV1,
    SessionCandidateMode,
    SessionCandidateRefV1,
    SessionCreateIntentV1,
    SessionCreateRequestV1,
    SessionDiscoveryScope,
    SessionIdentityCatalogPortV1,
    SessionIdentityEnvelopeV1,
    SessionIdentityProjectionV1,
)
from .errors import (
    AppHostError,
    AppHostFailureCategory,
    CleanupIncompleteError,
    GenerationConflictError,
    GenerationRetiredError,
    InvalidAppHostContractError,
    InvalidAppHostContractReason,
    ProductIdentityRequiredError,
    ProductIncompatibleError,
    ProductUnavailableError,
    SessionAmbiguousError,
    SessionCandidateStaleError,
)
from .router import AppHostRouterV1

__all__ = [
    "APPHOST_CONTRACT_VERSION",
    "SESSION_IDENTITY_ENVELOPE_VERSION",
    "AdmissionIdentityV1",
    "AdmissionGenerationLeaseV1",
    "AdmissionGenerationSourceV1",
    "AppHostCatalogV1",
    "AppHostAdmissionSubjectKind",
    "AppHostCatalogInputV1",
    "AppHostComponent",
    "AppHostError",
    "AppHostFailureCategory",
    "AppHostLifecycleTransition",
    "AppHostObservationSinkV1",
    "AppHostObservationV1",
    "AppHostRouterV1",
    "ClaimedSessionCandidateV1",
    "CleanupIncompleteError",
    "GenerationConflictError",
    "GenerationRetiredError",
    "InvalidAppHostContractError",
    "InvalidAppHostContractReason",
    "OpenedProductCandidateV1",
    "PreparedProductRouteV1",
    "ProductCandidateValidatorV1",
    "ProductCompatibilityImporterV1",
    "ProductDescriptorV1",
    "ProductFactoryV1",
    "ProductIdentityRequiredError",
    "ProductIncompatibleError",
    "ProductProfileBindingV1",
    "ProductRegistrationV1",
    "ProductUnavailableError",
    "ProfileDescriptorV1",
    "ProfileFactoryV1",
    "ProfileLeaseV1",
    "ProfileRegistrationV1",
    "ScopedProductRuntimeV1",
    "SessionBindingKeyV1",
    "SessionAmbiguousError",
    "SessionCandidateStaleError",
    "SessionCandidateLeaseV1",
    "SessionCandidateMode",
    "SessionCandidateRefV1",
    "SessionCreateIntentV1",
    "SessionCreateRequestV1",
    "SessionDiscoveryScope",
    "SessionIdentityCatalogPortV1",
    "SessionIdentityEnvelopeV1",
    "SessionIdentityProjectionV1",
]
