"""Product-neutral AppHost A0 contracts.

A0.1 intentionally exposes values and structural ports only. It contains no
catalog, router, live runtime owner, profile composer, launcher, or Product
activation path.
"""

from .contracts import (
    APPHOST_CONTRACT_VERSION,
    SESSION_IDENTITY_ENVELOPE_VERSION,
    AdmissionGenerationLeaseV1,
    AdmissionGenerationSourceV1,
    AdmissionIdentityV1,
    AppHostAdmissionSubjectKind,
    AppHostCatalogInputV1,
    AppHostComponent,
    AppHostLifecycleTransition,
    AppHostObservationSinkV1,
    AppHostObservationV1,
    ClaimedSessionCandidateV1,
    OpenedProductCandidateV1,
    ProductCandidateValidatorV1,
    ProductCompatibilityImporterV1,
    ProductDescriptorV1,
    ProductFactoryV1,
    ProductProfileBindingV1,
    ProductRegistrationV1,
    ProfileDescriptorV1,
    ProfileFactoryV1,
    ProfileLeaseV1,
    ProfileRegistrationV1,
    ScopedProductRuntimeV1,
    SessionBindingKeyV1,
    SessionCandidateLeaseV1,
    SessionCandidateMode,
    SessionCandidateRefV1,
    SessionCreateIntentV1,
    SessionCreateRequestV1,
    SessionDiscoveryScope,
    SessionIdentityCatalogPortV1,
    SessionIdentityEnvelopeV1,
    SessionIdentityProjectionV1,
)
from .errors import (
    AppHostError,
    AppHostFailureCategory,
    InvalidAppHostContractError,
    InvalidAppHostContractReason,
)

__all__ = [
    "APPHOST_CONTRACT_VERSION",
    "SESSION_IDENTITY_ENVELOPE_VERSION",
    "AdmissionIdentityV1",
    "AdmissionGenerationLeaseV1",
    "AdmissionGenerationSourceV1",
    "AppHostAdmissionSubjectKind",
    "AppHostCatalogInputV1",
    "AppHostComponent",
    "AppHostError",
    "AppHostFailureCategory",
    "AppHostLifecycleTransition",
    "AppHostObservationSinkV1",
    "AppHostObservationV1",
    "ClaimedSessionCandidateV1",
    "InvalidAppHostContractError",
    "InvalidAppHostContractReason",
    "OpenedProductCandidateV1",
    "ProductCandidateValidatorV1",
    "ProductCompatibilityImporterV1",
    "ProductDescriptorV1",
    "ProductFactoryV1",
    "ProductProfileBindingV1",
    "ProductRegistrationV1",
    "ProfileDescriptorV1",
    "ProfileFactoryV1",
    "ProfileLeaseV1",
    "ProfileRegistrationV1",
    "ScopedProductRuntimeV1",
    "SessionBindingKeyV1",
    "SessionCandidateLeaseV1",
    "SessionCandidateMode",
    "SessionCandidateRefV1",
    "SessionCreateIntentV1",
    "SessionCreateRequestV1",
    "SessionDiscoveryScope",
    "SessionIdentityCatalogPortV1",
    "SessionIdentityEnvelopeV1",
    "SessionIdentityProjectionV1",
]
