"""Lazy public exports for the optional Agent transcript profile."""

# ruff: noqa: F401 - TYPE_CHECKING imports preserve the typed public facade.

from __future__ import annotations

from importlib import import_module
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from loushang.harness.transcript.codecs import (
        STANDARD_PAYLOAD_VERSION,
        create_agent_transcript_message_codec,
        create_agent_transcript_payload_registry,
        register_standard_payload_codecs,
    )
    from loushang.harness.transcript.committer import (
        ApplicationMessageIdentityConflictError,
        CommitResult,
        TranscriptCommitter,
    )
    from loushang.harness.transcript.compaction import (
        TURN_AWARE_SUMMARY_IMPLEMENTATION,
        TURN_AWARE_SUMMARY_VERSION,
        AgentTranscriptCompactionCapability,
        TranscriptCompactionConfiguration,
        compaction_plan_to_json,
        create_agent_transcript_compaction_capability,
        plan_turn_aware_compaction,
        prepare_turn_aware_compaction,
    )
    from loushang.harness.transcript.context_usage import (
        ContextUsageSnapshot,
        build_context_usage_snapshot,
        calculate_context_tokens,
        current_context_usage,
        estimate_context_tokens,
        estimate_message_tokens,
        has_post_compaction_usage,
        latest_compaction_entry,
        model_context_window,
    )
    from loushang.harness.transcript.directory import (
        AgentTranscriptDirectoryRuntime,
        IndexRefreshFailureRecorder,
        SessionIndexPage,
        SessionIndexPageItem,
    )
    from loushang.harness.transcript.export import (
        HTML_TRANSCRIPT_DISPOSITIONS,
        TranscriptExportRequest,
        TranscriptHtmlExportProfile,
        TranscriptToolDefinition,
        export_agent_transcript_to_html,
        export_agent_transcript_to_jsonl,
        render_entry_tree,
        render_tool_sections,
        render_transcript,
    )
    from loushang.harness.transcript.interaction import (
        AgentTranscriptInspector,
        AgentTranscriptNavigationRuntime,
        AgentTranscriptSelectionRuntime,
        BranchSummaryOutput,
        BranchSummaryRunner,
        ModelSelectionCatalog,
        TranscriptForkCandidate,
        TranscriptMessageCounts,
        TranscriptNavigationPlan,
        TranscriptNavigationResult,
        application_message_text,
        assistant_message_text,
        model_selection_from_model,
        user_message_text,
        validate_model,
    )
    from loushang.harness.transcript.jsonl_file import (
        AgentTranscriptFileError,
        AgentTranscriptFileLayout,
        FilenameForKey,
        agent_transcript_file_lock,
        agent_transcript_journal,
        create_agent_transcript_file_store,
        create_agent_transcript_repository,
        load_agent_transcript_file,
        load_agent_transcript_header,
        load_agent_transcript_repository,
        write_agent_transcript_export,
    )
    from loushang.harness.transcript.kinds import (
        AGENT_MESSAGE_KIND,
        APPLICATION_MESSAGE_KIND,
        COMMAND_EXECUTION_KIND,
        CONTEXT_BRANCH_SUMMARY_KIND,
        CONTEXT_COMPACTION_CHECKPOINT_KIND,
        CONVERSATION_METADATA_PATCH_KIND,
        EXTENSION_DATA_KIND,
        MODEL_CALL_OUTCOME_KIND,
        MODEL_INPUT_COMPONENT_KIND,
        MODEL_INPUT_PREPARED_KIND,
        MODEL_SELECTION_KIND,
        RECORD_ANNOTATION_PATCH_KIND,
        STANDARD_AGENT_TRANSCRIPT_KINDS,
        THINKING_SELECTION_KIND,
    )
    from loushang.harness.transcript.lifecycle import (
        AgentTranscriptLifecycle,
        AgentTranscriptLifecycleContext,
        AgentTranscriptLifecycleSession,
        AgentTranscriptRuntimeBinding,
        delete_agent_transcript_jsonl,
    )
    from loushang.harness.transcript.maintenance import (
        AgentTranscriptCompactionRuntime,
        AutoCompactionOutcome,
        CompactionAborted,
        CompactionDecision,
        CompactionHookDecision,
        CompactionHookRequest,
        CompactionPlan,
        CompactionPreparation,
        CompactionResult,
        CompactionStatus,
        TranscriptCompactionPolicy,
        build_threshold_compaction_decision,
        is_compaction_aborted,
    )
    from loushang.harness.transcript.migration import (
        CURRENT_SESSION_VERSION,
        LEGACY_SESSION_OPAQUE_KIND,
        MigrationDisposition,
        SessionV3ImportResult,
        SessionV3MigrationError,
        SessionV3MigrationResult,
        convert_session_v3_snapshot,
        import_session_v3_file,
        is_conversation_jsonl_file,
        read_session_v3_file,
    )
    from loushang.harness.transcript.model_call import (
        ModelCallInvocationProjection,
        ModelCallInvocationState,
        project_model_call_invocations,
    )
    from loushang.harness.transcript.model_call_types import (
        MODEL_CALL_OUTCOME_SCHEMA_VERSION,
        ModelCallDisposition,
        ModelCallFailureInfo,
        ModelCallOutcome,
    )
    from loushang.harness.transcript.model_input import (
        ModelInputCommitContext,
        ModelInputCommitResult,
        ModelInputReconstructionVerification,
        ModelInputRuntimeReferences,
        ModelInputTranscriptCommitter,
        RebuiltModelInput,
        rebuild_model_input,
        verify_model_input,
    )
    from loushang.harness.transcript.model_input_types import (
        MODEL_INPUT_MAX_ENCODED_RECORD_BYTES,
        MODEL_INPUT_PROJECTION_VERSION,
        MODEL_INPUT_SCHEMA_VERSION,
        ModelInputComponent,
        ModelInputComponentReference,
        ModelInputIntegrityError,
        ModelInputRecordSizeError,
        ModelInputSnapshot,
    )
    from loushang.harness.transcript.model_input_v2_types import (
        MODEL_INPUT_V2_PAYLOAD_VERSION,
        ModelInputNodeBundle,
        ModelInputSnapshotV2,
    )
    from loushang.harness.transcript.product_session import (
        ProductTranscriptSession,
    )
    from loushang.harness.transcript.profile import (
        AgentTranscriptProfile,
        RecordSemantics,
        application_message_to_user_message,
        command_execution_to_text,
        context_item_to_model_message,
        context_items_to_model_messages,
        estimate_record_tokens,
        record_is_visible,
        record_role,
        record_to_context_item,
    )
    from loushang.harness.transcript.retry_runtime import (
        AgentTranscriptRetryRuntime,
        AutoRetryOutcome,
        is_retryable_assistant_error,
    )
    from loushang.harness.transcript.runtime_profile import (
        AgentTranscriptProfileRuntime,
        AgentTranscriptRuntimeSpec,
    )
    from loushang.harness.transcript.session import (
        AgentTranscriptSession,
        ApplicationMessageIdFactory,
        CommitObserver,
    )
    from loushang.harness.transcript.session_catalog import (
        AgentTranscriptSessionCatalog,
        SessionMetadata,
        SessionQuery,
        SessionRecord,
        SessionSummary,
        SessionTreeNode,
        agent_transcript_header_cwd,
        agent_transcript_header_parent_session,
        build_agent_transcript_label_indexes,
        build_agent_transcript_session_context,
        build_agent_transcript_session_tree,
        filter_agent_transcript_session_summaries,
        find_all_agent_transcript_session_summaries,
        find_all_indexed_agent_transcript_session_summaries,
        list_all_agent_transcript_session_summaries,
        list_all_indexed_agent_transcript_session_summaries,
        load_agent_transcript_session_metadata,
        project_agent_transcript_session_summary,
        project_session_record,
        refresh_all_agent_transcript_session_indexes,
        same_agent_transcript_session_path,
    )
    from loushang.harness.transcript.session_factory import (
        AgentTranscriptSessionFactory,
        BindingInputResolver,
        HeaderMetadataFactory,
        RestoredHeaderValidator,
        SessionFileFactory,
    )
    from loushang.harness.transcript.summarization import (
        DEFAULT_BRANCH_SUMMARY_PREAMBLE,
        BranchSummaryDelta,
        BranchSummaryPreparation,
        SummaryCompleter,
        SummaryDecoration,
        SummaryDecorator,
        SummaryResourceOperationDecorationProfile,
        collect_branch_summary_delta,
        collect_summary_resource_operations,
        decorate_summary_resource_operations,
        default_summary_completer,
        estimate_agent_message_tokens,
        execute_branch_summary,
        execute_transcript_compaction,
        normalize_branch_summary_output,
        prepare_branch_summary,
        serialize_agent_conversation,
    )
    from loushang.harness.transcript.types import (
        AgentTranscriptContext,
        AgentTranscriptPayload,
        AgentTranscriptRecord,
        AgentTranscriptState,
        AnnotationOperation,
        ApplicationDeliveryMode,
        ApplicationMessage,
        BranchContextSummary,
        ContentBlock,
        ContextCompactionCheckpoint,
        ConversationMetadataPatch,
        DecodedAgentTranscriptPayload,
        ExtensionData,
        ModelSelectionSnapshot,
        RecordAnnotationPatch,
        ThinkingSelectionSnapshot,
        application_message_content_blocks,
    )
    from loushang.harness.transcript.unit_of_work import (
        AgentTranscriptCommit,
        AgentTranscriptOpenDiagnostic,
        AgentTranscriptUnitOfWork,
    )
    from loushang.harness.transcript.writer import (
        AgentTranscriptRecordFactory,
        Clock,
        IdFactory,
    )

_EXPORT_MODULES = {
    "AutoCompactionOutcome": "loushang.harness.transcript.maintenance",
    "AGENT_MESSAGE_KIND": "loushang.harness.transcript.kinds",
    "APPLICATION_MESSAGE_KIND": "loushang.harness.transcript.kinds",
    "COMMAND_EXECUTION_KIND": "loushang.harness.transcript.kinds",
    "CONTEXT_BRANCH_SUMMARY_KIND": "loushang.harness.transcript.kinds",
    "CONTEXT_COMPACTION_CHECKPOINT_KIND": "loushang.harness.transcript.kinds",
    "CONVERSATION_METADATA_PATCH_KIND": "loushang.harness.transcript.kinds",
    "CURRENT_SESSION_VERSION": "loushang.harness.transcript.migration",
    "EXTENSION_DATA_KIND": "loushang.harness.transcript.kinds",
    "MODEL_INPUT_COMPONENT_KIND": "loushang.harness.transcript.kinds",
    "MODEL_INPUT_PREPARED_KIND": "loushang.harness.transcript.kinds",
    "MODEL_CALL_OUTCOME_KIND": "loushang.harness.transcript.kinds",
    "MODEL_CALL_OUTCOME_SCHEMA_VERSION": "loushang.harness.transcript.model_call_types",
    "MODEL_INPUT_MAX_ENCODED_RECORD_BYTES": "loushang.harness.transcript.model_input_types",
    "MODEL_INPUT_PROJECTION_VERSION": "loushang.harness.transcript.model_input_types",
    "MODEL_INPUT_SCHEMA_VERSION": "loushang.harness.transcript.model_input_types",
    "MODEL_INPUT_V2_PAYLOAD_VERSION": "loushang.harness.transcript.model_input_v2_types",
    "HTML_TRANSCRIPT_DISPOSITIONS": "loushang.harness.transcript.export",
    "MODEL_SELECTION_KIND": "loushang.harness.transcript.kinds",
    "LEGACY_SESSION_OPAQUE_KIND": "loushang.harness.transcript.migration",
    "RECORD_ANNOTATION_PATCH_KIND": "loushang.harness.transcript.kinds",
    "STANDARD_AGENT_TRANSCRIPT_KINDS": "loushang.harness.transcript.kinds",
    "STANDARD_PAYLOAD_VERSION": "loushang.harness.transcript.codecs",
    "THINKING_SELECTION_KIND": "loushang.harness.transcript.kinds",
    "TURN_AWARE_SUMMARY_IMPLEMENTATION": "loushang.harness.transcript.compaction",
    "TURN_AWARE_SUMMARY_VERSION": "loushang.harness.transcript.compaction",
    "AgentTranscriptContext": "loushang.harness.transcript.types",
    "AgentTranscriptDirectoryRuntime": "loushang.harness.transcript.directory",
    "SessionIndexPage": "loushang.harness.transcript.directory",
    "SessionIndexPageItem": "loushang.harness.transcript.directory",
    "AgentTranscriptCommit": "loushang.harness.transcript.unit_of_work",
    "AgentTranscriptOpenDiagnostic": "loushang.harness.transcript.unit_of_work",
    "AgentTranscriptCompactionCapability": "loushang.harness.transcript.compaction",
    "AgentTranscriptCompactionRuntime": "loushang.harness.transcript.maintenance",
    "AgentTranscriptFileError": "loushang.harness.transcript.jsonl_file",
    "AgentTranscriptFileLayout": "loushang.harness.transcript.jsonl_file",
    "AgentTranscriptLifecycle": "loushang.harness.transcript.lifecycle",
    "AgentTranscriptLifecycleContext": "loushang.harness.transcript.lifecycle",
    "AgentTranscriptLifecycleSession": "loushang.harness.transcript.lifecycle",
    "AgentTranscriptInspector": "loushang.harness.transcript.interaction",
    "AgentTranscriptNavigationRuntime": "loushang.harness.transcript.interaction",
    "AgentTranscriptPayload": "loushang.harness.transcript.types",
    "AgentTranscriptProfile": "loushang.harness.transcript.profile",
    "AgentTranscriptProfileRuntime": "loushang.harness.transcript.runtime_profile",
    "AgentTranscriptRecord": "loushang.harness.transcript.types",
    "AgentTranscriptRecordFactory": "loushang.harness.transcript.writer",
    "AgentTranscriptRetryRuntime": "loushang.harness.transcript.retry_runtime",
    "AutoRetryOutcome": "loushang.harness.transcript.retry_runtime",
    "AgentTranscriptRuntimeBinding": "loushang.harness.transcript.lifecycle",
    "AgentTranscriptRuntimeSpec": "loushang.harness.transcript.runtime_profile",
    "AgentTranscriptSelectionRuntime": "loushang.harness.transcript.interaction",
    "AgentTranscriptUnitOfWork": "loushang.harness.transcript.unit_of_work",
    "AgentTranscriptSession": "loushang.harness.transcript.session",
    "AgentTranscriptSessionCatalog": "loushang.harness.transcript.session_catalog",
    "AgentTranscriptSessionFactory": "loushang.harness.transcript.session_factory",
    "AgentTranscriptState": "loushang.harness.transcript.types",
    "AnnotationOperation": "loushang.harness.transcript.types",
    "ApplicationDeliveryMode": "loushang.harness.transcript.types",
    "ApplicationMessage": "loushang.harness.transcript.types",
    "ApplicationMessageIdFactory": "loushang.harness.transcript.session",
    "ApplicationMessageIdentityConflictError": "loushang.harness.transcript.committer",
    "BranchContextSummary": "loushang.harness.transcript.types",
    "BranchSummaryDelta": "loushang.harness.transcript.summarization",
    "BranchSummaryOutput": "loushang.harness.transcript.interaction",
    "BranchSummaryPreparation": "loushang.harness.transcript.summarization",
    "BranchSummaryRunner": "loushang.harness.transcript.interaction",
    "BindingInputResolver": "loushang.harness.transcript.session_factory",
    "Clock": "loushang.harness.transcript.writer",
    "CommitResult": "loushang.harness.transcript.committer",
    "CommitObserver": "loushang.harness.transcript.session",
    "CompactionDecision": "loushang.harness.transcript.maintenance",
    "CompactionHookDecision": "loushang.harness.transcript.maintenance",
    "CompactionHookRequest": "loushang.harness.transcript.maintenance",
    "CompactionAborted": "loushang.harness.transcript.maintenance",
    "CompactionPlan": "loushang.harness.transcript.maintenance",
    "CompactionPreparation": "loushang.harness.transcript.maintenance",
    "CompactionResult": "loushang.harness.transcript.maintenance",
    "CompactionStatus": "loushang.harness.transcript.maintenance",
    "ContentBlock": "loushang.harness.transcript.types",
    "ContextCompactionCheckpoint": "loushang.harness.transcript.types",
    "ContextUsageSnapshot": "loushang.harness.transcript.context_usage",
    "DEFAULT_BRANCH_SUMMARY_PREAMBLE": "loushang.harness.transcript.summarization",
    "ConversationMetadataPatch": "loushang.harness.transcript.types",
    "DecodedAgentTranscriptPayload": "loushang.harness.transcript.types",
    "ExtensionData": "loushang.harness.transcript.types",
    "FilenameForKey": "loushang.harness.transcript.jsonl_file",
    "IdFactory": "loushang.harness.transcript.writer",
    "IndexRefreshFailureRecorder": "loushang.harness.transcript.directory",
    "HeaderMetadataFactory": "loushang.harness.transcript.session_factory",
    "ModelSelectionSnapshot": "loushang.harness.transcript.types",
    "ModelInputCommitContext": "loushang.harness.transcript.model_input",
    "ModelInputCommitResult": "loushang.harness.transcript.model_input",
    "ModelInputComponent": "loushang.harness.transcript.model_input_types",
    "ModelInputComponentReference": "loushang.harness.transcript.model_input_types",
    "ModelInputIntegrityError": "loushang.harness.transcript.model_input_types",
    "ModelInputRecordSizeError": "loushang.harness.transcript.model_input_types",
    "ModelInputReconstructionVerification": "loushang.harness.transcript.model_input",
    "ModelInputRuntimeReferences": "loushang.harness.transcript.model_input",
    "ModelInputSnapshot": "loushang.harness.transcript.model_input_types",
    "ModelInputNodeBundle": "loushang.harness.transcript.model_input_v2_types",
    "ModelInputSnapshotV2": "loushang.harness.transcript.model_input_v2_types",
    "ModelInputTranscriptCommitter": "loushang.harness.transcript.model_input",
    "ModelCallInvocationProjection": "loushang.harness.transcript.model_call",
    "ModelCallInvocationState": "loushang.harness.transcript.model_call",
    "ModelCallDisposition": "loushang.harness.transcript.model_call_types",
    "ModelCallFailureInfo": "loushang.harness.transcript.model_call_types",
    "ModelCallOutcome": "loushang.harness.transcript.model_call_types",
    "ModelSelectionCatalog": "loushang.harness.transcript.interaction",
    "MigrationDisposition": "loushang.harness.transcript.migration",
    "ProductTranscriptSession": "loushang.harness.transcript.product_session",
    "RecordAnnotationPatch": "loushang.harness.transcript.types",
    "RecordSemantics": "loushang.harness.transcript.profile",
    "RebuiltModelInput": "loushang.harness.transcript.model_input",
    "SessionV3MigrationError": "loushang.harness.transcript.migration",
    "SessionV3ImportResult": "loushang.harness.transcript.migration",
    "SessionV3MigrationResult": "loushang.harness.transcript.migration",
    "SessionMetadata": "loushang.harness.transcript.session_catalog",
    "SessionFileFactory": "loushang.harness.transcript.session_factory",
    "SessionQuery": "loushang.harness.transcript.session_catalog",
    "SessionRecord": "loushang.harness.transcript.session_catalog",
    "SessionSummary": "loushang.harness.transcript.session_catalog",
    "SessionTreeNode": "loushang.harness.transcript.session_catalog",
    "SummaryCompleter": "loushang.harness.transcript.summarization",
    "SummaryDecoration": "loushang.harness.transcript.summarization",
    "SummaryDecorator": "loushang.harness.transcript.summarization",
    "RestoredHeaderValidator": "loushang.harness.transcript.session_factory",
    "ThinkingSelectionSnapshot": "loushang.harness.transcript.types",
    "TranscriptCompactionPolicy": "loushang.harness.transcript.maintenance",
    "TranscriptCompactionConfiguration": "loushang.harness.transcript.compaction",
    "TranscriptExportRequest": "loushang.harness.transcript.export",
    "TranscriptForkCandidate": "loushang.harness.transcript.interaction",
    "TranscriptHtmlExportProfile": "loushang.harness.transcript.export",
    "TranscriptMessageCounts": "loushang.harness.transcript.interaction",
    "TranscriptNavigationPlan": "loushang.harness.transcript.interaction",
    "TranscriptNavigationResult": "loushang.harness.transcript.interaction",
    "TranscriptToolDefinition": "loushang.harness.transcript.export",
    "TranscriptCommitter": "loushang.harness.transcript.committer",
    "application_message_content_blocks": "loushang.harness.transcript.types",
    "application_message_text": "loushang.harness.transcript.interaction",
    "application_message_to_user_message": "loushang.harness.transcript.profile",
    "assistant_message_text": "loushang.harness.transcript.interaction",
    "agent_transcript_header_cwd": "loushang.harness.transcript.session_catalog",
    "agent_transcript_header_parent_session": "loushang.harness.transcript.session_catalog",
    "agent_transcript_file_lock": "loushang.harness.transcript.jsonl_file",
    "agent_transcript_journal": "loushang.harness.transcript.jsonl_file",
    "command_execution_to_text": "loushang.harness.transcript.profile",
    "compaction_plan_to_json": "loushang.harness.transcript.compaction",
    "context_item_to_model_message": "loushang.harness.transcript.profile",
    "context_items_to_model_messages": "loushang.harness.transcript.profile",
    "current_context_usage": "loushang.harness.transcript.context_usage",
    "build_agent_transcript_label_indexes": "loushang.harness.transcript.session_catalog",
    "build_agent_transcript_session_context": "loushang.harness.transcript.session_catalog",
    "build_agent_transcript_session_tree": "loushang.harness.transcript.session_catalog",
    "convert_session_v3_snapshot": "loushang.harness.transcript.migration",
    "create_agent_transcript_payload_registry": "loushang.harness.transcript.codecs",
    "create_agent_transcript_message_codec": "loushang.harness.transcript.codecs",
    "create_agent_transcript_compaction_capability": "loushang.harness.transcript.compaction",
    "create_agent_transcript_file_store": "loushang.harness.transcript.jsonl_file",
    "create_agent_transcript_repository": "loushang.harness.transcript.jsonl_file",
    "delete_agent_transcript_jsonl": "loushang.harness.transcript.lifecycle",
    "build_context_usage_snapshot": "loushang.harness.transcript.context_usage",
    "build_threshold_compaction_decision": "loushang.harness.transcript.maintenance",
    "calculate_context_tokens": "loushang.harness.transcript.context_usage",
    "collect_branch_summary_delta": "loushang.harness.transcript.summarization",
    "collect_summary_resource_operations": "loushang.harness.transcript.summarization",
    "estimate_context_tokens": "loushang.harness.transcript.context_usage",
    "estimate_agent_message_tokens": "loushang.harness.transcript.summarization",
    "estimate_message_tokens": "loushang.harness.transcript.context_usage",
    "estimate_record_tokens": "loushang.harness.transcript.profile",
    "export_agent_transcript_to_html": "loushang.harness.transcript.export",
    "export_agent_transcript_to_jsonl": "loushang.harness.transcript.export",
    "execute_branch_summary": "loushang.harness.transcript.summarization",
    "execute_transcript_compaction": "loushang.harness.transcript.summarization",
    "decorate_summary_resource_operations": "loushang.harness.transcript.summarization",
    "filter_agent_transcript_session_summaries": "loushang.harness.transcript.session_catalog",
    "find_all_agent_transcript_session_summaries": "loushang.harness.transcript.session_catalog",
    "find_all_indexed_agent_transcript_session_summaries": "loushang.harness.transcript.session_catalog",
    "import_session_v3_file": "loushang.harness.transcript.migration",
    "is_conversation_jsonl_file": "loushang.harness.transcript.migration",
    "is_compaction_aborted": "loushang.harness.transcript.maintenance",
    "is_retryable_assistant_error": "loushang.harness.transcript.retry_runtime",
    "list_all_agent_transcript_session_summaries": "loushang.harness.transcript.session_catalog",
    "list_all_indexed_agent_transcript_session_summaries": "loushang.harness.transcript.session_catalog",
    "load_agent_transcript_session_metadata": "loushang.harness.transcript.session_catalog",
    "load_agent_transcript_file": "loushang.harness.transcript.jsonl_file",
    "load_agent_transcript_repository": "loushang.harness.transcript.jsonl_file",
    "load_agent_transcript_header": "loushang.harness.transcript.jsonl_file",
    "model_selection_from_model": "loushang.harness.transcript.interaction",
    "model_context_window": "loushang.harness.transcript.context_usage",
    "normalize_branch_summary_output": "loushang.harness.transcript.summarization",
    "plan_turn_aware_compaction": "loushang.harness.transcript.compaction",
    "prepare_turn_aware_compaction": "loushang.harness.transcript.compaction",
    "project_model_call_invocations": "loushang.harness.transcript.model_call",
    "prepare_branch_summary": "loushang.harness.transcript.summarization",
    "SummaryResourceOperationDecorationProfile": "loushang.harness.transcript.summarization",
    "read_session_v3_file": "loushang.harness.transcript.migration",
    "record_is_visible": "loushang.harness.transcript.profile",
    "record_role": "loushang.harness.transcript.profile",
    "project_agent_transcript_session_summary": "loushang.harness.transcript.session_catalog",
    "project_session_record": "loushang.harness.transcript.session_catalog",
    "refresh_all_agent_transcript_session_indexes": "loushang.harness.transcript.session_catalog",
    "same_agent_transcript_session_path": "loushang.harness.transcript.session_catalog",
    "has_post_compaction_usage": "loushang.harness.transcript.context_usage",
    "latest_compaction_entry": "loushang.harness.transcript.context_usage",
    "record_to_context_item": "loushang.harness.transcript.profile",
    "rebuild_model_input": "loushang.harness.transcript.model_input",
    "render_entry_tree": "loushang.harness.transcript.export",
    "render_tool_sections": "loushang.harness.transcript.export",
    "render_transcript": "loushang.harness.transcript.export",
    "serialize_agent_conversation": "loushang.harness.transcript.summarization",
    "register_standard_payload_codecs": "loushang.harness.transcript.codecs",
    "write_agent_transcript_export": "loushang.harness.transcript.jsonl_file",
    "user_message_text": "loushang.harness.transcript.interaction",
    "default_summary_completer": "loushang.harness.transcript.summarization",
    "validate_model": "loushang.harness.transcript.interaction",
    "verify_model_input": "loushang.harness.transcript.model_input",
}


def __getattr__(name: str) -> Any:
    """Resolve a public symbol without eagerly loading the whole profile."""

    try:
        module_name = _EXPORT_MODULES[name]
    except KeyError as exc:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}") from exc
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted({*globals(), *_EXPORT_MODULES})


__all__ = list(_EXPORT_MODULES)
