"""Stable record kinds for the default Agent transcript profile."""

AGENT_MESSAGE_KIND = "agent.message"
THINKING_SELECTION_KIND = "agent.thinking_selection"
MODEL_SELECTION_KIND = "agent.model_selection"
COMMAND_EXECUTION_KIND = "command.execution"
CONTEXT_COMPACTION_CHECKPOINT_KIND = "context.compaction_checkpoint"
CONTEXT_BRANCH_SUMMARY_KIND = "context.branch_summary"
APPLICATION_MESSAGE_KIND = "application.message"
EXTENSION_DATA_KIND = "extension.data"
RECORD_ANNOTATION_PATCH_KIND = "record.annotation_patch"
CONVERSATION_METADATA_PATCH_KIND = "conversation.metadata_patch"
MODEL_INPUT_COMPONENT_KIND = "model.input.component"
MODEL_INPUT_PREPARED_KIND = "model.input.prepared"
MODEL_CALL_OUTCOME_KIND = "model.call.outcome"

STANDARD_AGENT_TRANSCRIPT_KINDS = (
    AGENT_MESSAGE_KIND,
    THINKING_SELECTION_KIND,
    MODEL_SELECTION_KIND,
    COMMAND_EXECUTION_KIND,
    CONTEXT_COMPACTION_CHECKPOINT_KIND,
    CONTEXT_BRANCH_SUMMARY_KIND,
    APPLICATION_MESSAGE_KIND,
    EXTENSION_DATA_KIND,
    RECORD_ANNOTATION_PATCH_KIND,
    CONVERSATION_METADATA_PATCH_KIND,
    MODEL_INPUT_COMPONENT_KIND,
    MODEL_INPUT_PREPARED_KIND,
    MODEL_CALL_OUTCOME_KIND,
)

__all__ = [
    "AGENT_MESSAGE_KIND",
    "APPLICATION_MESSAGE_KIND",
    "COMMAND_EXECUTION_KIND",
    "CONTEXT_BRANCH_SUMMARY_KIND",
    "CONTEXT_COMPACTION_CHECKPOINT_KIND",
    "CONVERSATION_METADATA_PATCH_KIND",
    "EXTENSION_DATA_KIND",
    "MODEL_INPUT_COMPONENT_KIND",
    "MODEL_INPUT_PREPARED_KIND",
    "MODEL_CALL_OUTCOME_KIND",
    "MODEL_SELECTION_KIND",
    "RECORD_ANNOTATION_PATCH_KIND",
    "STANDARD_AGENT_TRANSCRIPT_KINDS",
    "THINKING_SELECTION_KIND",
]
